### ISSUE TITLE
Foreign linking / FFI

### ISSUE THREAD

**Issue by rossberg** [dfinity/motoko#1400]
This is a tracking issue for adding the ability to Motoko to interoperate with foreign code on an intra-canister level.

Some high-level design considerations:
* Cross language interop would naturally be provided at Wasm module boundaries, by supporting cross-language linking.
* For that we'll probably need to define some language-agnostic ABI/IDL, similar to Candid but for modules.
* We should keep track of the ongoing [interface types proposal](https://github.com/WebAssembly/interface-types/blob/linking/proposals/interface-types/Explainer.md) for Wasm, which is trying to solve the same problem for the Wasm ecosystem at large. However, it's still in early stages, and not entirely clear how well it will suite our needs.

Implementation considerations:
* A prerequisite is that Motoko supports separate compilation; currently, the compiler performs whole-program compilation.
* The Motoko compiler already has some specialised linking mechanism for the language's runtime system (RTS), which is written in C. However, this is not exposed and probably not general or robust enough in its current form.
* As we're adding more features to the Motoko base library, more flexible linking against foreign modules may become relevant for the language impl itself, e.g., to incorporate existing math, unicode, or database libraries.

Related: #147, #452.

**Comment by ggreif** [comment]
Just a random thought, would `wasm { ... }` blocks fill in any use-case (other than providing an unsafe exit hatch)? If one can extrapolate from ancient C times, such a lowest-level construct gave many game programmers the extra bit of performance they needed to make tight loops feasible. (I am not proposing such a feature, and I can totally see how it would open a huge can of worms.)

**Comment by luc-blaeser** [comment]
We consider using Wasm component model for intra-canister language interop (and sandboxing e.g. multiple unsafe Rust components). Tracking this separately as Wasm component model. This also needs IC extensions.
