### ISSUE TITLE
Check upgrade compatibility of internal, stable interfaces

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#1430]
We need to implement a tool that checks that the internal stable, interface of an upgrade is compatible with the internal, stable interface of the upgraded canister. 

This boils down to checking that the new stable interface is (roughly) a supertype of the old stable interface so that installs of the upgrade will accept the stable store of the upgraded canister..

See related Issue #1429

**Comment by rossberg** [comment]
This has been done as well.
