### ISSUE TITLE
Type-indexed sharing in stable serialization

### ISSUE THREAD

**Issue by nomeata** [dfinity/motoko#1497]
With #1483 we alias mutable values (which, thanks to invariance, can only occur at a single type).  For immutable values, this doesn’t quite work, as alias’ed values might be serialized at different types.

We can keep track of sharing _for each type_, using the type hash (#1493). This way we can preserve some sharing (although not all).

**Comment by luc-blaeser** [comment]
Solved with enhanced orthogonal persistence
