### ISSUE TITLE
GC: Use a page allocator to avoid extra copy

### ISSUE THREAD

**Issue by nomeata** [dfinity/motoko#1670]
Currently our GC works like this:

We begin with
```
[stack][static data][from-space]← End of Wasm memory
```
then GC copies to `to-space`:
```
[stack][static data][dead-space][to-space]← End of Wasm memory
```
and then it copied `to-space` into `dead-space` (with a simple memcopy, i.e. the updates pointers already take that into account):
```
[stack][static data][to-space]\/[dead space]← End of Wasm memory
```
where `\/` marks the “end of heap” where we begin allocation.

Better would be the following:
After 
```
[stack][static data][dead-space][to-space]← End of Wasm memory
```
we go to
```
[stack][static data]\/[dead-space][to-space]← End of Wasm memory
```
i.e. don’t move `to-space` again, but instead begin allocating at `\/`.

After a while we have:
```
[stack][static data][live]\/[dead][live]← End of Wasm memory
```
and if the next thing we want to allocate is bigger than `[dead]`, we probably have to this:
```
[stack][static data][live][dead(slack)][live]\/ ← End of Wasm memory
```
i.e. move the end-of-heap until the end of memory and maybe request more pages from the system, and the small `[dead]` becomes wasted slack.

I can’t quite wrap my head around what happens after many GCs. Will the number of regions to be tracked (as dead or alive) grow, or are they bounded? Will the slack regions clean up again? 

So maybe takes this as a starting point to think this through :-)

**Comment by luc-blaeser** [comment]
Superseded by incremental GC
