### ISSUE TITLE
Bad error message when importing `.did` that isn't a service

### ISSUE THREAD

**Issue by nomeata** [dfinity/motoko#2319]
Users out there ran into an exception: https://forum.dfinity.org/t/build-error-with-imported-actor-class/1931

They built a canister using `actor class…`, which produced this `.did`:
```
type anon_class_1_1 = 
 service {
 };
service : () -> anon_class_1_1
```
which then tripped this code:
```
    match actor with
    | Some {it=ServT ms; _} ->
       let fs = List.map (check_meth env) ms in
       let fs = M.Env.fold (fun id t fs ->
         match t with
         | M.Con (c, _) -> M.{lab = id; typ = M.Typ c}::fs
         | _ -> assert false) !m_env fs in
       M.Obj (M.Actor, List.sort M.compare_field fs)
    | None -> assert false
    | _ -> assert false 
```

These `assert false` should produce more helpful error messages.

(Of course, we also should support importing canister classes, but that's a bigger thing; this issue is _just_ about proper error messages.)

**Comment by nomeata** [comment]
People keep running into this (https://forum.dfinity.org/t/motoko-compiler-bug/5095). We should at least produce a helpful error message.

**Comment by crusso** [comment]
That's weird, I too thought this had been fixed (or, at least, the error improved).

**Comment by nomeata** [comment]
Maybe there was a hard fork in the universe's reality?

**Comment by chenyan-dfinity** [comment]
Weird, I also remember there was a PR to improve the error message....

**Comment by crusso** [comment]
> hmm, should this be an error or we can be more permissive that when `import canister:` for an `actor class`, it refers to the canister instantiated by the actor class (strip out the init arguments); when `import class:` for an `actor class`, it refers to the uninstantiated actor class.

I'm with @chenyan-dfinity on this one. If the code is written as a class then importing a canister of that class could just strip the argument. We don't support importing of actor classes via `import "canister:"` and using `import "class:"` would arguably be more appropriate anyway.

**Comment by crusso** [comment]
The confusion is already baked into to the language design. A class declaration both names the type of its instances (an actor) and the name of a constructor (a function). Canister import can just be interpreted as importing an actor or instance of a class.

**Comment by matthewhammer** [comment]
>  this issue is just about proper error messages.

Reminder.
