### ISSUE TITLE
Allow explicit imports

### ISSUE THREAD

**Issue by kritzcreek** [dfinity/motoko#2354]
**Story**

As a developer, I want to be able to explicitly import unqualified types and functions from other modules.

**Motivation**

Currently we can only import modules as a whole with a qualified identifier.
This leads to a lot of `Result.Result` which looks silly, and makes people create module local private aliases.
This is bad because:

1.  They're adding boilerplate to work around compiler limitations
2.  They don't get hyperlinked documentation because their type signatures point to module local private type definitions.

**Demo**
I want something like this to compile
``` Motoko
    import Result "Result";
    // Showcases both type as well as value level imports
    import { type Result, mkErr } "Result";
    
    module {
      public fun fromOption<Ok, Err>(err: Err, opt: ?Ok) : Result<Ok, Err> {
        switch opt {
          case null { mkErr(err) };
          case (?ok) { Result.mkOk(ok) };
        };
      };
    }
```

**Design**

This doesn't *just work* if we allow object patterns, because we can't project type components that way.

It might also be nice to have a more compact format for the "import both as qualified and explicit" pattern, as shown above.

**Comment by ggreif** [comment]
Wouldn't this be an instance of an `and` pattern with the small twist that the LHS is a label pattern (appearing in the record to be destructured) and that only applies to record values?
