### ISSUE TITLE
CI: Create Github releases from CI

### ISSUE THREAD

**Issue by nomeata** [dfinity/motoko#2566]
We should configure our Github Actions that that 
 * when a new tag is created
 * and the tag looks like a release
 * and the release artifacts built (probably in separate steps for linux and darwin)
 * we automatically create a new Github release and include the files with that release, in a format and naming convention that works for `vessel`
 * bonus points for extracting the relevant section from the `Changelog.md` and using is in the release.

This should be documented in <./CI.md>.

@kritzcreek mentioned that he has done this before. Can you point to prior art that we can cargo-cult?

**Comment by nomeata** [comment]
@kritzcreek , should the file name of the artifacts include the version:
```
https://github.com/nomeata/motoko/releases/download/0.1.2/motoko-linux64-0.1.2.tar.gz
```
or not
```
https://github.com/nomeata/motoko/releases/download/0.1.2/motoko-linux64.tar.gz
```

**Comment by kritzcreek** [comment]
No strong preference

**Comment by nomeata** [comment]
Same here, that’s why I am asking you :-D

I have implemented the former now, but I wonder if the latter is nicer

**Comment by kritzcreek** [comment]
Go for the former. It duplicates the version in the Url, but makes it so the artifact is still "meaningful" after downloading.
