### ISSUE TITLE
Candid subtype check during deserialization

### ISSUE THREAD

**Issue by nomeata** [dfinity/motoko#2582]
Looks like don’t have an issue for this yet…

In https://github.com/dfinity/candid/pull/168 the Candid rules were changed to require a dynamic eager subtyping check during serialization. And we should implement this.

I believe that we should first build the infrastructure for type representations (https://github.com/dfinity/motoko/issues/2348), and then re-implement the deserialization on top of that. The current implementation scheme is not well suited for this subtyping check.

**Comment by nomeata** [comment]
With https://github.com/dfinity/candid/pull/311 this will look different again. Subtype checks are now boolean (instead of producing a coercion function), do can be done in rust if preferred, and no Motoko type rep is needed.

**Comment by ggreif** [comment]
@crusso is this resolved now?

**Comment by crusso** [comment]
Yep

**Comment by crusso** [comment]
Fixed by https://github.com/dfinity/motoko/pull/3171
