### ISSUE TITLE
dfinity-ci reports in PRs are no longer reliable

### ISSUE THREAD

**Issue by osa1** [dfinity/motoko#2631]
I realized today that @dfinity-ci's comments on binary size and perf changes are no longer reliable, I think it always says "This PR does not affect the produced WebAssembly code.". For example: https://github.com/dfinity/motoko/pull/2573#issuecomment-864967187 No idea what's wrong but perhaps it's related to the refactorings in the CI setup for open sourcing.

cc @crusso

**Comment by osa1** [comment]
I think we should prioritize this. I'm worried that without automatic checking for binary sizes and perf we'll accumulate large increases in binaries / decreases in perf over time.

**Comment by nomeata** [comment]
Since this check relies on `drun`, and that is only available to people with access to the internal repos, I don’t think I can help alot with debugging this. Still hoping to see `drun` here soon: https://github.com/dfinity/ic/tree/master/rs

**Comment by nomeata** [comment]
The PR https://github.com/dfinity/motoko/pull/2573  seems to just change testing infrastructure, so I wouldn’t expect that PR to change the actual output of the compiler (didn’t look at the diff though), so “This PR does not affect the produced WebAssembly code” seems to be correct.

But I guess https://github.com/dfinity/motoko/pull/2641#issuecomment-872333379 is an indication that something is wrong.

My guess: These two jobs succeed, but don’t produce any `.wasm` (e.g. wrong compiler flags):
```
  wasm-hash-base = wasm-hash-for baseJobs.moc;
  wasm-hash-pr = wasm-hash-for prJobs.moc;
```
then this kicks in
```
      if cmp -s ${wasm-hash-base} ${wasm-hash-pr}
      then
        echo "This PR does not affect the produced WebAssembly code." >> $out/report
      else
        diff-stats ${baseJobs.tests.perf}/stats.csv ${prJobs.tests.perf}/stats.csv > $out/report;
      fi
```
and prevents showing the diff.

This is from `ci-pr.nix`.

**Comment by nomeata** [comment]
Fix in https://github.com/dfinity/motoko/pull/2643
