### ISSUE TITLE
Doc: Ascii.doc rendering of some operators (especially involving =) is totally broken

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#2635]
https://sdk.dfinity.org/docs/language-guide/language-manual.html#syntax-ops for some obvious examples.

Looks like APL!

**Comment by chenyan-dfinity** [comment]
Although I love APL, https://github.com/dfinity/antora-sdk/pull/41 may be the reason? Not sure.

**Comment by crusso** [comment]
Could be, but I think it was actual us just failing to understand asciidoc.

**Comment by crusso** [comment]
@chenyan-dfinity would that explain why the examples here look wrong (assignment and equality render badly in the displayed code)

**Comment by nomeata** [comment]
This looks like it’s using a font with code ligatures: https://github.com/tonsky/FiraCode

So it’s not a bug, it’s a feature…

**Comment by crusso** [comment]
Oh, I misread the calculator code and thought it was rendering `:=` badly, but that's actually `/=`. Still I don't think stuff like:

![image](https://user-images.githubusercontent.com/85788/124585368-1fa9c580-de4d-11eb-8a38-f9c033503087.png)

is helpful.

**Comment by crusso** [comment]
Unfortunately, I tried to fix this here https://github.com/dfinity/motoko/pull/2636. I wonder what that will look like now...
