### ISSUE TITLE
Consider using cargo-wasi for tests

### ISSUE THREAD

**Issue by osa1** [dfinity/motoko#2637]
Currently RTS test suite is implemented as an application because `cargo test --target=wasm32-wasi` does not work:

```
    Finished test [unoptimized + debuginfo] target(s) in 0.40s
     Running target/wasm32-wasi/debug/deps/motoko_rts_tests-0c4efb283f8bdbaf.wasm
/home/omer/dfinity/motoko/rts/motoko-rts-tests/target/wasm32-wasi/debug/deps/motoko_rts_tests-0c4efb283f8bdbaf.wasm: 1: /home/omer/dfinity/motoko/rts/motoko-rts-tests/target/wasm32-wasi/debug/deps/motoko_rts_tests-0c4efb283f8bdbaf.wasm: Syntax error: end of file unexpected
error: test failed, to rerun pass '--bin motoko-rts-tests'
```

I haven't tried yet, but I think with [cargo-wasi][1] `cargo wasi test` should work. If it does then we can start using Rust's built-in testing features to get nice test output, test filtering etc. for free. Currently if I'm working on GC I have to manually comment-out tests for other features to get quick feedback. Test outputs are also implemented manually and so takes effort.

It should also allow us to merge the test and library crates. That should simplify the build scripts (nix, `rts/Makefile`).

[1]: https://github.com/bytecodealliance/cargo-wasi

**Comment by luc-blaeser** [comment]
I think we should mostly focus on full Motoko testing, i.e. allow to test (and later maybe even debug) Motoko canisters. Closing this for now if okay.
