### ISSUE TITLE
Defaults for types

### ISSUE THREAD

**Issue by skilesare** [dfinity/motoko#2645]
This is probably a dupe, but I did search.

It would be really nice to have default values for types as discussed in https://forum.dfinity.org/t/initializing-an-object-with-optional-nullable-fields/1790.

I'd like to be able to something like:

    Public type myType= {
       Operation : {
           #noOp*;
           #add;
           #sub;};
       Delay: Nat*(100);
       
    };

Or some other better symbol.

**Comment by rossberg** [comment]
Copying my answer from the thread you reference:

> Following its pitfall avoidance philosophy, it is intentional that Motoko requires to be explicit about all initialisation, whether variables or fields. Default initialisation is a common source for bugs, since forgetting proper initialisation can happen by accident. And like all implicit behaviour, it obscures code for readers, who may not easily see what's going, or can't tell whether it was intended.

So there is no intention to add the particular feature you're asking for. As mentioned in the thread, however, we want to add something like record update.
