### ISSUE TITLE
Array.sort/sortInPlace vanished from Array module

### ISSUE THREAD

**Issue by rossberg** [dfinity/motoko#2659]
For some odd reason, the sort functions are missing from the type of the Array module, although they exist in the library.

See https://forum.dfinity.org/t/array-sort-is-not-available-when-programming-motoko/5868 

(I can indeed reproduce this with the playground.)

**Comment by crusso** [comment]
This was just dfx 0.7.2 shipping a rather old moc 0.6.1.

The sort functions should be available from dfx 0.7.6 onwards (and are also now available in the playground, i.e.

```
import Array "mo:base/Array";
import Nat "mo:base/Nat"

actor {
    public func sort() : async Text {
        let a = Array.sort([2, 1, 3], Nat.compare);
        let b = [var 2, 1, 3];
        Array.sortInPlace(b, Nat.compare);
        return debug_show({ a; b});
    };
};
```

works just fine.
