### ISSUE TITLE
Motoko error message is not self-explanatory for empty input

### ISSUE THREAD

**Issue by ehsan6sha** [dfinity/motoko#2666]
When calling a method with zero input we receive the following error:
‘Canister xxx trapped explicitly : IDL error: empty input’

Per discussion below, it is not self-explanatory.
https://forum.dfinity.org/t/canister-xxx-trapped-explicitly-idl-error-empty-input/6002

Merging pull request below can resolve it:
https://github.com/dfinity/motoko/pull/2665

**Comment by crusso** [comment]
Thanks for the report and fix!
