### ISSUE TITLE
[Bug] Large Nat32 literal overflow in JS

### ISSUE THREAD

**Issue by chenyan-dfinity** [dfinity/motoko#2671]
The following code raise an exception in `int_of_big_int` in Motoko Playground. 

```
actor {
    let a: Nat32 = 0x80000000; // raise int_of_big_int
    let b: Nat64 = 0x80000000; // okay
    let c: Nat32 = 0x7fffffff; // okay
};
```

Not necessarily a compiler bug, but would be nice if we can support this in `js_of_ocaml` somehow. The exception only happens when a `Nat32` literal is larger than 28 bits. The interpreter in JS works fine though. 

cc @ggreif

**Comment by ggreif** [comment]
We don't have many uses of `int_of_big_int` in `moc`:
```
$ git grep int_of_big_int
src/codegen/compile.ml:          [ Int32.of_int (Big_int.int_of_big_int b) ] @ go a
src/mo_values/numerics.ml:  let to_int = int_of_big_int
src/mo_values/numerics.ml:    else power_big_int_positive_int x (int_of_big_int y)
src/mo_values/prim.ml:    let i = Big_int.int_of_big_int i in
```
I am trying to narrow down which one is causing this. There is a possibility that it comes from another library altogether, though not probable.

**Comment by ggreif** [comment]
@chenyan-dfinity I wonder where the 28 bit arise. https://ocaml.org/api/Sys.html#VALint_size mentions 31 and 32 (on JS).

**Comment by ggreif** [comment]
I tried Motoko Playground, and with your code deployment gets stuck after:
> [17:03:35] Compiling code...

I wonder where do you get the piece of information from the log that `int_of_big_int` is the culprit.

**Comment by chenyan-dfinity** [comment]
You can see the error from console.log, e.g. Tools/Developer Tools in Chrome.

**Comment by chenyan-dfinity** [comment]
> Also, 0x7fffffff seems like 31 trailing binary ones.

Ah, right. It's 31bit. Maybe your fix works, i.e. use Int32 instead of int.

**Comment by chenyan-dfinity** [comment]
That can be caught by the frontend? By the time it reaches codegen, we are safe.

**Comment by ggreif** [comment]
Yeah, sure, that is fine, but you still want `Nat32` in Motoko, so we should handle it. Btw. I see in the playground there is no `try`-`catch` around `const out = await worker.Moc({ type:"compile", file });`, is this by design?

**Comment by chenyan-dfinity** [comment]
I tried the JS code after #2682, it's still the same. Probably expected, because the number we convert there is 28 bits. The exception most likely comes from `mo_value`. Is it difficult to convert int to Int32 in mo_value?

**Comment by ggreif** [comment]
It would definitely help to extract a stack trace...

**Comment by ggreif** [comment]
It appears that `Int.to_int` gets called (`numerics.ml:221`) with a `Big_int` of `0x80000000`. This cannot be represented as `int` (= `Int.t`) on systems with 31-bits. JS is probably such a system. Not a problem with `moc` as it only runs on 64-bit systems. I wonder why the webpage-embedded interpreter works, though.

**Comment by chenyan-dfinity** [comment]
This means if we compile `moc` on 32-bit systems, we will get the same error? Is the interpreter using the same `mo_value` representation?

**Comment by ggreif** [comment]
That is my working assumption.

**Comment by ggreif** [comment]
This is one backtrace (I am using `assert` on a 64-bit system)
```
Raised at Mo_values__Numerics.Int.to_int in file "mo_values/numerics.ml", line 221, characters 17-71
Called from Codegen__Compile.const_lit_of_lit in file "codegen/compile.ml", line 6135, characters 48-73
Called from Codegen__Compile.compile_const_exp in file "codegen/compile.ml", line 7928, characters 33-57
Called from Codegen__Compile.compile_const_dec in file "codegen/compile.ml", line 7976, characters 24-54
Called from Codegen__Compile.compile_dec in file "codegen/compile.ml", line 7832, characters 23-55
```

**Comment by ggreif** [comment]
These look fishy:
```
  | Int32Lit n    -> Const.Word32 (Int32.of_int (Numerics.Int_32.to_int n))
  | Nat32Lit n    -> Const.Word32 (Int32.of_int (Numerics.Nat32.to_int n))
```
we should do what is done here:
```
  | Int64Lit n    -> Const.Word64 (Big_int.int64_of_big_int (Numerics.Int_64.to_big_int n))
  | Nat64Lit n    -> Const.Word64 (Big_int.int64_of_big_int (nat64_to_int64 (Numerics.Nat64.to_big_int n)))
```

**Comment by ggreif** [comment]
@chenyan-dfinity please verify that #2686 does the right thing in the playground.
