### ISSUE TITLE
Support the heartbeat

### ISSUE THREAD

**Issue by nomeata** [dfinity/motoko#2728]
@roman-kashitsyn [leaked on the forum](https://forum.dfinity.org/t/ic-cron-lets-schedule-some-tasks-bois/6506/6?u=nomeata) that the `canister_heartbeat` entry point is now supported by application subnets. The Interface spec doesn’t list it yet, but once it’s there we should probably support it from Motoko.

Unless we take the stance (from the discussion on the feature in the `ic-ref` at https://github.com/dfinity-lab/ic-ref/issues/245, which I can’t read any more) that `canister_heartbeat` is a low-level feature meant to be used mainly by canisters providing cron services to other canisters, and that Motoko canisters should not use this (inefficient, inflexible) interface, but should rather use dedicated cron-as-a-service-canisters.

But the pragmatic thing is probably to expose the `canister_heartbeat` entry point.

**Comment by crusso** [comment]
Shouldn't be too hard to support.

**Comment by nomeata** [comment]
Yeah, the straight forward exposition should be almost trivial. 

Is our type system strong enough to express a context that allows calls (i.e. can await), but does not allow responses? That might new, or affect the default reject handler.

**Comment by crusso** [comment]
Not entirely sure, but it sounds like the same restrictions we enforce on oneways by forcing the ignore async {...} abomination.

**Comment by FloorLamp** [comment]
Hi Claudio, any chance we can get this added? Right now I have to install a separate rust heartbeat canister to call my motoko ones, this isn't very ideal 😅

**Comment by ninegua** [comment]
Here is my very naive & hacky attempt at implementing it https://github.com/ninegua/motoko/commit/6a0a645b467dbaf5e4d1d6da7d6aed66dc60b8a1

Probably made a lot of mistakes, and I don't have time to write any test case. It is better wait for official implementation.

**Comment by crusso** [comment]
@ninegua thanks for that! Looks quite plausible (skimming only)

 @rossberg shall we add support for the heartbeat method?

**Comment by crusso** [comment]
(I would probably make it just return `(0)`, not `async()`, like a oneway though.)

**Comment by rossberg** [comment]
Fine by me!

**Comment by ninegua** [comment]
> (I would probably make it just return (), not async(), like a oneway though.)

That was my first try. But with only `()` I cannot make it pass the type checker if I have `await ..` in the function body. Maybe you can help?

Also my suggestion is to rename `upgrade { .. }` record to `system { ... }` to better match the intention.

**Comment by jzxchiang1** [comment]
Any update on this? Thanks!

**Comment by Motokoder** [comment]
Please give my canister a heartbeat.
