### ISSUE TITLE
Idea: remove size computation in serialization, serialize in one pass

### ISSUE THREAD

**Issue by osa1** [dfinity/motoko#2797]
Currently we do serialization in two passes. First pass computes buffer size. We then allocate a blob with the computed buffer size and serialize to that blob.

This two-pass implementation relies on being able to write an offset or address value to object headers, and that we can distinguish offsets/addresses from object tags. These offsets/addresses are used to preserve sharing of mutable variables during serialization and avoid looping.

~~This causes problems with #2790 (which is needed for #2706). With #2790 we no longer have a 32-bit space in headers available to the serializers.~~ See my comment below.

If we make serialization work in one pass it solves the issues with overwriting object headers to preserve sharing and avoid looping, and also allows putting more information in object headers in #2790.

Here's how it would work:

- We will need a "linked buffer" data type. Serialization code will start with a fixed-size buffer, and extend it by allocating new blobs and linking them to the previous buffer chunk. We will also need a function for writing these linked buffers to the stable memory, using one `ic0.stable_write` per chunk in the list.

- Serialization will use this new buffer type, and allocate new chunks as needed.

- After that we will no longer need the size computation, because we can now grow the buffer as needed. We can start with e.g. 1 KiB buffer, and either extend it by allocating same sized chunks, or maybe add 1.5 KiB, then 3 KiB and so on.

- For sharing, we use the "forwarding pointer" tag that the copying GC uses. Whenever we see a mutable variable, we serialize it, and update the object in heap with a forwarding pointer. The forwarding pointer will have the offset of the object's serialization, **in the final, linear, serialization buffer**. In other words, if the buffer is written to **stable memory address** `N` and the serialization of the mutable variable will be in `N+M` in the stable memory, the field will have value `M`.

  (We could also introduce a new tag for this, but I'm not sure that's necessary)

- (Previous step will leave the serialized objects in an inconsistent state, but I think that's OK as these objects won't be traced by the GC)

- No changes needed in deserialization

**Changes to runtime:** We won't need a pass for computing the size, so that's a win. Writes will need to check the buffer size, and grow the buffer as needed. We currently do not check the buffer size and assume it has the right size (i.e. the buffer size pass is correct), so this will be extra cycles used in runtime. We should check the size and grow as needed in batches. For example: do one "grow_buffer" call for N writes that will write in total M words, then do unchecked writes in those N writes. (not sure what the max. value of N here, I suspect it won't be too big)

Unclear whether the net result will be a positive or negative.

Writing to stable memory will be done in multiple steps, instead of one step. I doubt this will be a problem though, we could tweak buffer size to minimize number of calls. Hard to say for sure without numbers. It would be helpful to know buffer sizes of some of the real-world Motoko canisters, and max. seen so far.

Deserialization will work as before.

**Changes to binary sizes:** Unclear whether it'll grow or shrink. We will remove the code for the size computation, but add code for (1) the linked buffer implementation (2) for growing the buffer as needed during serialization. Note that buffer size functions are generated per type, so removing this pass removes one function per serialized type. So I expect this change to be a win for binary sizes.

**Changes to memory usage:** 2 word overhead per buffer chunk. Should be negligible.

**Comment by osa1** [comment]
Right after posing this I realized that if it's OK to leave serialized objects in an inconsistent state (one of my assumption in my design above) then we don't need to worry about overwriting the header bits for gc metadata.

Having one-pass implementation might still be worthwhile though.

**Comment by crusso** [comment]
Interesting idea. This would still be necessary if we allowed programmatic serialization of extended (mutable)  Candid to blobs, but we don't yet and I don't see why we would want to.

**Comment by crusso** [comment]
We could also abuse the Text ropes for binary buffer, I suspect.

**Comment by nomeata** [comment]
Yes yes yes. I have always wanted something like that; buffered serialization, and writing out the serialized data in chunks. This will also greatly improve candid encoding when encoding a message argument or reply, if one doesn't need a separate buffer that contains the full result, but just smaller chunks. And I assume that blobs and texts can be written out to the reply/stable memory directly, without copying. After all, that's why defined the system API to allow chunked writes!

So all for it. I just didn't do it so far because it's “just” an optimization, and adds complexities (managing these buffers, flushing them, etc). But once there isn't anything more important to do, yes, please.

**Comment by luc-blaeser** [comment]
As for stabilization, this has been obsolete with enhanced orthogonal persistence.
