### ISSUE TITLE
Adopt 128 bit cycles API

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#2833]
https://dfinity.atlassian.net/browse/LANG-8

**Comment by crusso** [comment]
@nomeata do you recall: what's the current status of support wasm functions with n-ary returns at the moment? The new 128 bit cycles API returns two values, high and low 64 bits, presumably for atomicity, and I'm wondering if I'll be able to call that using our wasm lib or will need to upgrade.

**Comment by nomeata** [comment]
That requires multi-value, see https://github.com/dfinity/motoko/pull/1459. I am surprised that this actually works in the replica, I thought rust support for multi-value is not there yet. 

I see nothing in `ic-hs` yet. I'd wait before it's there before doing anything in Motoko (or officially give up on spec and reference implementation driven design).

Do they have test cases with plain `.wat` files that demonstrate that the replica really implements the specification (with multiple results), and not sure Rust-specific calling convention that uses the stack or something like that?

**Comment by crusso** [comment]
Yeah, I though I might be being too optimistic....  I'll have to investigate I guess...

**Comment by nomeata** [comment]
Once https://github.com/dfinity/motoko/pull/2879 is merged we have support for this in `ic-ref`. Support in `drun` is still blocked on a working public code dump.

**Comment by crusso** [comment]
Long done.
