### ISSUE TITLE
Candid decoder: Fail if principals are large

### ISSUE THREAD

**Issue by nomeata** [dfinity/motoko#2875]
The public spec says that  [principals are at most 29  bytes](https://sdk.dfinity.org/docs/interface-spec/index.html#principal) in  length, but the [Motoko Candid decoder](https://github.com/dfinity/motoko/blob/6feb52696bd7c446a7fe5231519045dd6d248bdc/src/codegen/compile.ml#L5031) does not check that.

This may lead to DOS vulnerabilities where a developer does not expect that attackers can send very large values (up to the message size limit) here.

Also applies to the `principal` in a service or function reference.

Suggested fix: add a `read_principal` helper function (like `read_blob`) that traps if the size is more than 29 bytes.

**Comment by nomeata** [comment]
Oh, sorry, @ggreif,  I didn’t see the self-assignent and just fixed it.

**Comment by ggreif** [comment]
I don't really feel assaulted! Thanks! :-)
