### ISSUE TITLE
Marking in mark-compact GC can be optimized (one-two instructions per live object)

### ISSUE THREAD

**Issue by osa1** [dfinity/motoko#2892]
Currently we convert an address to a bitmap index with `(address - heap_base) / word_size`: https://github.com/dfinity/motoko/blob/939a539539d234c601ced48da949004c46774580/rts/motoko-rts/src/gc/mark_compact.rs#L133

It's possible to eliminate two instructions (local load, subtraction) in this operation by doing `address / word_size` instead. This requires allocating slightly larger bitmaps for the heap below `heap_base`. 

One Wasm page needs 8,192 bytes (8 KiB) in the bitmap. `heap_base` is often 1 Wasm page (Rust/C stack) + a few more bytes for the literals (strings, bytes) in the canister.

Thanks @ulan for the idea.

**Comment by ggreif** [comment]
Two questions:
- instead of increasing the bitmap sizes, why not keep a global `bitmap_base` pointer around, that points to a lower location to compensate?
- could we use `WORD_SIZE * 2`-granularity bitmaps, or do we have heap objects that only consist of a single word?

**Comment by nomeata** [comment]
No, all dynamically allocated heap objects are at least 2 words, but they may be of odd word size. It you want to half the bitmap like this, all allocation needs to be aligned, and you might waste a word
