### ISSUE TITLE
GC: Avoid pushing large array fields when marking arrays

### ISSUE THREAD

**Issue by osa1** [dfinity/motoko#2903]
Currently in mark-compact GC (soon again the default collector), when marking an array, we push all elements of the array to the mark stack.

For large arrays this can be problematic as mark stack can grow quite large.

Instead, if we push something like `(array offset, array end)` to the mark stack, the unmarked range of the array will be represented as one entry in the mark stack.

The main question is how to represent this pair `(array offset, array end)` without making every other entry in the mark stack one word larger.

Note that when pushing a `(array offset, array end)` pair for an array for the first time, we should mark every element in the range (similar to how we mark objects when pushing to the mark stack). This is to avoid pushing these objects to the mark stack in the case where every object in the array is also referenced by other objects in the heap. In that case if we push `(array offset, array end)` without marking the elements in the range, it is possible that we will visit other objects that refer to the objects referenced by the array and end up pushing all of them to the stack, basically ending up with where we started.

**Comment by matthewhammer** [comment]
The proposal makes sense, even without me fully appreciating the implementation (yet).

I'm curious about what we can say about the best case behavior for this proposal?   Mainly, I want to confirm that I see the benefit clearly.

Suppose that the heap is mostly a huge array-based hash table, and there is no cycle from which we can travel through the array more than once (entering initially from some root pointer, for instance).  Suppose there are `N` entries in the table.

In that case, for a system with `N` records, we avoid pushing `O(N)` on the mark stack, but will "eagerly" visit each of those locations rather than use the mark stack to remember to visit them (the current behavior, IIUC).

So, if the mark stack is supposed to be something like at most `O(log N)`, then this improvement works, by letting us operate within that bound, and avoid growing it, and potentially running out of resources.

But this leads me to wonder what is the most pathological data structure for the new mark stack.  Suppose that I fill memory with a graph of small records, and no arrays?  That's outside of the scope of this issue, but is there another one that tracks it?

**Comment by osa1** [comment]
> In that case, for a system with N records, we avoid pushing O(N) on the mark stack, but will "eagerly" visit each of those locations rather than use the mark stack to remember to visit them (the current behavior, IIUC).

Eagerly visiting all the fields of an array will be worse in some cases. Suppose the array has 10,000 elements. If you push array elements to the mark stack (as we do today) you will push 10,000 objects. If you eagerly visit those objects instead of pushing them to the mark stack, depending on how many fields the elements have, so you will end up pushing more than 10,000, because each of those 10,000 elements will potentially have a few fields.

What I suggest is we push a pair of `(array offset, array end)` first, then mark some of the elements. Here's an example:

Suppose I have an array at 0x100000 with 100,000 elements. So the end of the array is 0x161a84.

When we pop 0x100000 we check the type and see that it's an array, in this code:

https://github.com/dfinity/motoko/blob/81c016e7c180ec78231d84f1f3fc9d8a66a690f7/rts/motoko-rts/src/visitor.rs#L26

Instead of pushing all of its pointer fields (as we do in the linked code), we push `(0x100198, 0x161a84)`, then push 100 elements (exact number to be decided). 0x161a84 is the end of the array, and 0x100198 is the address of the next element in the array after the first 100 elements.

(We need to push the pair first, and then the elements, otherwise the it will be the same as pushing all of the array elements as we do in master branch today, we just do it more inefficiently)

Then when we pop this pair, we again mark 100 elements starting from the first element of the pair (0x100198), and push `(0x100328, 0x161a84)` and so on, until we mark the entire array.

> So, if the mark stack is supposed to be something like at most O(log N), then this improvement works, by letting us operate within that bound, and avoid growing it, and potentially running out of resources.
>
> But this leads me to wonder what is the most pathological data structure for the new mark stack. Suppose that I fill memory with a cyclic graph of small records, and no arrays? That's outside of the scope of this issue, but is there another one that tracks it?

Currently in master branch, the worst case is you have a huge array that points to 1-word objects. In this case the mark stack size will be half of the heap size.

With the proposed idea in this issue implemented, the worst case will be smaller depending on how many elements we push to the mark stack when we pop an array, in my example above it's 100.

I think the new worst case will be array of array of array of ... arrays, or an object (rather than array) with a lot of fields. If the second case is common, we could apply the same idea to other objects/records/etc. too.

I think cycles are not relevant when discussing the worst case for mark stack size, because we never push an object to the mark stack twice.

**Comment by ggreif** [comment]
I believe we can represent the pairs of values standing for array slices as not pointers, but differently tagged values. Since we only push skewed pointers onto the mark stack, a different tagging should be easily recognisable, at the cost of a runtime test.

**Comment by luc-blaeser** [comment]
Resolved in all our scanning GCs, by slicing arrays during marking and updating
