### ISSUE TITLE
Can we also get rid of shifted (when `Vanilla`) `Bool`?

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#2906]
Since the first page in Wasm heap is reserved as stack/scratch area for RTS use, the number `1 : U32` won't be traced by the GC _ever_. Can we move back and say that `true` is `1 : U32` in `SR.Vanilla` too?

(Which similarly would allow us to also represent `Nat8` unshifted, but let's not open that can of worms just yet.)

**Comment by nomeata** [comment]
Good observation. I hope the abstractions in our code wouldn't make this change hard.
