### ISSUE TITLE
Bug: Documentation of 'range' 

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#2920]
` range(x : Nat, y : Int)` allows `Int` as the upper bound. There’s probably a reason that makes it easier to use. But anyway, in other parts of the documentation (here: https://smartcontracts.org/docs/language-guide/control-flow.html) it says the upper bound is `Nat`:
 As a constructor function, `range` has a function type:
 
 `(lower:Nat, upper:Nat) -> Iter<Nat>`

**Comment by timohanke** [comment]
Also `revrange` in one part of the documentation is `revRange(x : Int, y : Int)` and in another part it says:
```
As a constructor function, it has a function type:

(upper:Nat, lower:Nat) -> Iter<Nat>
```
