### ISSUE TITLE
Pattern inference crash when variant `switch` alternative contradicts scrutinee's type

### ISSUE THREAD

**Issue by borovan** [dfinity/motoko#2934]
Stderr:
OOPS! You've triggered a compiler bug.
Please report this at https://github.com/dfinity/motoko/issues/new with the following details:

Motoko 0.6.14 (source i5rk4rv7-xsrcz16w-6xp3834q-icgfd9zl)

Fatal error: exception (Invalid_argument Type.as_variant_sub)
Raised at Mo_types__Type.invalid in file "mo_types/type.ml", line 357, characters 16-54
Called from Mo_frontend__Typing.check_pat' in file "mo_frontend/typing.ml", line 1804, characters
 41-67
Called from Mo_frontend__Typing.check_pat in file "mo_frontend/typing.ml", line 1747, characters 
11-32
Called from Mo_frontend__Typing.check_pat in file "mo_frontend/typing.ml", line 1747, characters 
11-32
Called from Mo_frontend__Typing.check_case in file "mo_frontend/typing.ml", line 1630, characters
 11-34
Called from Stdlib__list.iter in file "list.ml", line 110, characters 12-15
Called from Mo_frontend__Typing.check_exp' in file "mo_frontend/typing.ml", line 1451, characters
 4-30
Called from Mo_frontend__Typing.check_exp in file "mo_frontend/typing.ml", line 1351, characters 
11-45
Called from Mo_frontend__Typing.check_dec in file "mo_frontend/typing.ml", line 2223, characters 
4-23
Called from Mo_frontend__Typing.recover_with in file "mo_frontend/typing.ml", line 77, characters
 56-59
Called from Mo_frontend__Typing.recover in file "mo_frontend/typing.ml" (inlined), line 79, chara
cters 18-37
Called from Mo_frontend__Typing.check_block_exps in file "mo_frontend/typing.ml", line 2217, char
acters 4-38
Called from Mo_frontend__Typing.recover_with in file "mo_frontend/typing.ml", line 77, characters
 56-59
Called from Mo_frontend__Typing.check_block in file "mo_frontend/typing.ml", line 2205, character
s 2-47
Called from Mo_frontend__Typing.check_exp' in file "mo_frontend/typing.ml", line 1442, characters
 11-42
Called from Mo_frontend__Typing.check_exp in file "mo_frontend/typing.ml", line 1351, characters 
11-45
Called from Mo_frontend__Typing.infer_exp'' in file "mo_frontend/typing.ml", line 1119, character
s 6-57
Called from Mo_frontend__Typing.infer_exp' in file "mo_frontend/typing.ml", line 885, characters 
10-29
Called from Mo_frontend__Typing.infer_exp in file "mo_frontend/typing.ml" (inlined), line 869, ch
aracters 2-31
Called from Mo_frontend__Typing.infer_dec in file "mo_frontend/typing.ml", line 2147, characters 
4-21
Called from Mo_frontend__Typing.check_dec in file "mo_frontend/typing.ml", line 2226, characters 
13-30
Called from Mo_frontend__Typing.recover_with in file "mo_frontend/typing.ml", line 77, characters
 56-59
Called from Mo_frontend__Typing.recover in file "mo_frontend/typing.ml" (inlined), line 79, chara
cters 18-37
Called from Mo_frontend__Typing.infer_block_exps in file "mo_frontend/typing.ml", line 2139, char
acters 24-58
Called from Mo_frontend__Typing.infer_block in file "mo_frontend/typing.ml", line 2120, character
s 10-55
Called from Mo_frontend__Typing.infer_obj in file "mo_frontend/typing.ml", line 2002, characters 
17-40
Called from Mo_frontend__Typing.infer_exp' in file "mo_frontend/typing.ml", line 885, characters 
10-29
Called from Mo_frontend__Typing.infer_exp in file "mo_frontend/typing.ml" (inlined), line 869, ch
aracters 2-31
Called from Mo_frontend__Typing.infer_dec in file "mo_frontend/typing.ml", line 2147, characters 
4-21
Called from Mo_frontend__Typing.infer_block in file "mo_frontend/typing.ml", line 2120, character
s 10-55
Called from Mo_frontend__Typing.check_lib.(fun) in file "mo_frontend/typing.ml", line 2563, chara
cters 23-59
Called from Mo_frontend__Typing.recover_opt.(fun) in file "mo_frontend/typing.ml", line 78, chara
cters 55-60
Called from Mo_frontend__Typing.recover_with in file "mo_frontend/typing.ml", line 77, characters
 56-59
Called from Diag.with_message_store in file "lang_utils/diag.ml", line 82, characters 10-13
Called from Pipeline.check_lib in file "pipeline/pipeline.ml", line 200, characters 16-41
Called from Pipeline.chase_imports.go in file "pipeline/pipeline.ml", line 362, characters 22-41
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.traverse_ in file "lang_utils/diag.ml", line 48, characters 20-25
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Pipeline.chase_imports.go in file "pipeline/pipeline.ml", line 360, characters 18-37
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.traverse_ in file "lang_utils/diag.ml", line 48, characters 20-25
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Pipeline.chase_imports.go_set in file "pipeline/pipeline.ml" (inlined), line 391, cha
racters 20-42
Called from Pipeline.chase_imports in file "pipeline/pipeline.ml", line 393, characters 47-63
Called from Pipeline.load_progs in file "pipeline/pipeline.ml", line 401, characters 21-52
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Diag.bind in file "lang_utils/diag.ml", line 32, characters 27-30
Called from Pipeline.compile_files in file "pipeline/pipeline.ml", line 678, characters 27-71
Called from Moc.process_files in file "exes/moc.ml", line 188, characters 49-94
Called from Moc in file "exes/moc.ml", line 282, characters 4-23

**Comment by borovan** [comment]
this is what i was working on

```
  public type StatIndex = {
    #armour; #carry; #damage; #flow; #health; #move;
  };

```

**Comment by borovan** [comment]
```
  // Modifier
  // A Modifier is applied to a ?
  public type Modifier = {
    stat : StatIndex;
    value : {
      #add : Int16;
      #multiply : PercentModifier;
    };
  };
```

**Comment by borovan** [comment]
```
  //
  // Stat
  //
  public class Stat(db : DB) : Entity<T.Stat> {
    public func store() : Store<T.Stat> { db.stat };
    public func create(d : T.Stat) : T.Stat {
      return {
        metadata = createMD();
        name = SGame.gameName(d.name);
        description = SGame.gameDescription(d.description);
        index = d.index;
        icon = d.icon;
      };
    };
    public func update(d : T.Stat) : T.Stat {
      return {
        metadata = updateMD(d.metadata);
        name = SGame.gameName(d.name);
        description = SGame.gameDescription(d.description);
        index = d.index;
        icon = d.icon;
      };
    };
    public func validate(d : T.Stat) : Result {
      let r = Result.Map();
      r.add("name", VGame.gameName(d.name));
      r.add("description", VGame.gameDescription(d.name));
      r.result();
    };
    public func relations(d : T.Stat) : Result {
      let r = Result.Map();
      r.add("icon", hasOne<T.Icon>(d.icon, Icon(db)));
      r.result();
    };
  };

```

**Comment by borovan** [comment]
I have found the offending code.  It was using an old validator function that had not been changed for the new structure of the Modifier type.

`  // Modifier
  public func modifier(v : T.Modifier) : Result {
    let r = Result.Map();
    switch (v) {

      // additive
      case (#armourAdd(v)) { r.add("armourAdd", VInt.range(v, -10, 10)) };
      case (#carryAdd(v)) { r.add("carryAdd", VInt.range(v, -10, 10)) };
      case (#damageAdd(v)) { r.add("damageAdd", VInt.range(v, -10, 10)) };
      case (#flowAdd(v)) { r.add("flowAdd", VInt.range(v, -10, 10)) };
      case (#healthAdd(v)) { r.add("healthAdd", VInt.range(v, -10, 10)) };
      case (#moveAdd(v)) { r.add("moveAdd", VInt.range(v, -10, 10)) };

      // percent
      case (#armourPercent(v)) {
        r.add("armourPercent", percentModifier(v));
      };
      case (#carryPercent(v)) {
        r.add("carryPercent", percentModifier(v));
      };
      case (#damagePercent(v)) {
        r.add("damagePercent", percentModifier(v));
      };
      case (#flowPercent(v)) {
        r.add("flowPercent", percentModifier(v));
      };
      case (#healthPercent(v)) {
        r.add("healthPercent", percentModifier(v));
      };
      case (#movePercent(v)) {
        r.add("movePercent", percentModifier(v));
      };
    };

    r.result();
  };`

**Comment by borovan** [comment]
I changed the modifier() validation function to this and it compiles fine :

```
  // Modifier
  public func modifier(v : T.Modifier) : Result {
    let r = Result.Map();
    switch (v.modifier) {
      case (#add x) { r.add("add", VInt.int16Range(x, -10, 10)) };
      case (#percent x) { r.add("percent", percentModifier(x)) };
    };

    r.result();
  };
```

**Comment by borovan** [comment]
simple repro using the latest moc (dfx 0.8.5-beta.0)

```
  public type Modifier = {
    modifier : {
      #add : Int;
      #percent : Nat;
    };
  };

  public func asplode(v : Modifier) {
      switch (v) {
          case (#fart v) {};
      }
  };
```

**Comment by ggreif** [comment]
Fun. The inference for `switch` want a `#fart`, but the `v : Modifier` only offers `#add` or `#percent`.

Now that you resolved this yourself (Thanks!) I assume this is not urgent any more, so I'll leave the fixing this for a long winter evening...

**Comment by ggreif** [comment]
I bet you can further remove the `#percent : Nat;` line.

**Comment by borovan** [comment]
yeah hah
```
  public type Modifier = {};
  public func asplode(v : Modifier) {
    switch (v) {
      case (#fart) {};
    }
  };
```
ok no rush!  Thanks a lot for checking

**Comment by ggreif** [comment]
Thanks for reporting! This really shouldn't crash but give you a nice diagnostic.

**Comment by ggreif** [comment]
This is even weirder: `public type Modifier = {}` is an empty _record_, not even a variant!

**Comment by ggreif** [comment]
Okay reducing further: 
- `switch "dd"  { case (#fart) {};  case 5 {} };` --> crash
- `switch (#fart)  { case (#fart) {};  case 5 {} };` --> type error
- `switch 5  { case (#fart) {};  case 5 {} };` --> crash

**Comment by rossberg** [comment]
The bug is fairly simple: the call to as_variant_sub in typing.ml#1804 is missing a suitable try/catch that can produce an error message "tag pattern cannot consume expected type" (like is present for the other pattern cases in that function).

I don't have time to fix it right now, so feel free to go ahead.
