### ISSUE TITLE
Cycle consumption recording problem

### ISSUE THREAD

**Issue by leo-icp** [dfinity/motoko#2936]
When I recorded the consumption of cycles, I found a very strange problem.
Motoko is a reactor model, should there be no concurrency problems? Or maybe it appears?

[https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=3143301081](https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=3143301081)

This is my demo code,
Execute after I deploy the code
If I click call once and wait for the result to execute, the result is what I want

But when I clicked it multiple times quickly, the result was the same as the picture.
There are fewer cycles before the execution of the loop than after the execution of the loop

**Comment by leo-icp** [comment]
https://forum.dfinity.org/t/cycle-consumption-recording-problem/9089

**Comment by rossberg** [comment]
Hm, which picture are you referring to?

**Comment by tuvs85** [comment]
> Hm, which picture are you referring to?

These 2 questions both describe a problem
The problem on the forum was because I couldn't find anyone to solve it, so I came to github to find the answer.

**Comment by leo-icp** [comment]
> Hm, which picture are you referring to?

![image](https://user-images.githubusercontent.com/73073736/143561926-1352396b-8d6c-4127-882f-c75e3c1658b0.png)

**Comment by leo-icp** [comment]
When I use async await to get the data and hashmap to store the sh. A more amazing problem occurs, I can't even get my cycles。
![image](https://user-images.githubusercontent.com/73073736/143563490-2b9921d2-1296-4e26-a472-43bfde6cad9e.png)

[https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=3662302706](https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=3662302706)

**Comment by rossberg** [comment]
I don't know exactly how the Playground manages cycles, @chenyan-dfinity would know more. But I would be very careful with drawing any conclusions from what you see here, since it may be doing some automatic topping up in the background. (Maybe it shouldn't even provide access to the cycles balance, because it might be misleading.)

**Comment by chenyan-dfinity** [comment]
The playground doesn't do anything while the user is in possession of the canister. But what you observed here is expected. Atomicity is only at the message level, not at the application method level. I replied in the forum for better visibility.
