### ISSUE TITLE
Implementing a generational copying GC on top of page allocator (#2706)

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#2958]
(copied from live edits here: https://hackmd.io/s/SJrB4eSKK)

Original Author:  Ömer Sinan Ağacan (@osa1)

Here I describe just one way of implementing a copying generational GC, using
page allocator implemented in #2706.

## Key concepts

Reference: The GC Handbook.

Descriptions below are in my words. When confused, please refer to The GC
Handbook.

- **Age of an object**: How many times the object survived GC.

- **Generation/generational**: Generational means we split heap into regions.
  These regions are called "generations". Generations are numbered
  incrementally, starting with 0. When we do a GC, instead of collecting the
  whole heap, we decide how many generations to collect. If we want collect N
  generations, then we collect generations `[0,N)`.

  The algorithm described here doesn't allow collecting all subsets of
  generations. We always collect generations `[0,N)` for some `N > 0`.

- **Evacuation**: Same as in current copying GC, but an object may be evacuated
  to a different generation than its current generation. See below for details.

- **Promotion**: When an object in generation `N` is evacuated to generation
  `N+1`, it's called promotion.

- **Eager promotion**: In some cases we want to evacuate an object in
  generation N to generation M, where M > N + 1. This is called eager
  promotion.

- **Major GC**: Collecting all of the generations.

- **Minor GC**: Not collecting one or more of the generations.

- **Remembered set**: In a GC algorithm where only some of the heap is
  collected, we need to keep track of objects in collected regions that are
  pointed by uncollected regions, and keep those objects alive.

  Remembered sets are one way to maintain such pointers. A generation other
  than the youngest will have a remembered set. When an object is mutated (i.e.
  a field is updated with a pointer value), the mutated object is added to the
  remembered set of its generation.

  In a GC, remembered sets of uncollected generations are treated as roots.

- **Write barrier:** Code that runs before or after a heap mutation (i.e.
  inserting a value to an object field, or an array).

  https://github.com/dfinity/motoko/pull/2702 tries to find all the places in
  the compiler and the runtime system where we do heap mutation.

- **Aging**: If we want to keep new allocations in generation 0 for more than
  one GC, that's called "aging". Aging = N means new allocations stay in
  generation 0 for N collections.

## Memory manager concepts

These are also summarized in https://github.com/dfinity/motoko/pull/2706.

Discussion below is slightly simplified and ignores large objects.

- **Large object**: An object that is too large to copy. Ideally we want to
  avoid copying these objects and implement some kind of mark-sweep style
  collection.

- **Page**: A memory region, a few words smaller than 64 KiB. Each page has a
  few words metadata at the beginning. The rest is used by **spaces** for
  allocation.

- **Space**: A memory region that supports allocation. Internally a `Space` is
  a list of pages, with a "heap pointer" pointing at next free space in the
  current page.

  Initially a space has one page. It allocates new pages as we allocate into
  the space and fill the current page.

`Space` and `Page` types have various methods to support copying and
mark-compact collections.

A special `Space` called `ALLOCATION_SPACE` is used directly by the mutator
(Motoko code) to allocate new objects.

## Implementing a generational GC using `Space` and `Page` types

Each generation will be a `Space`.

`Space` type will be extended with a new field for the "remembered set" for the
generation. For `ALLOCATION_SPACE` this field won't be used as (1) it can't
point to a younger generation (2) it will be collected always.

After an update message we decide how many generations to collect (0 or more, 0
meaning no GC). I don't know how to decide on this. We will probably need to
start with a conservative algorithm, then improve it based on benchmarks and
experimentation, as we did for the current scheduler.

After deciding how many generations to collect, we run the standard copying GC
algorithm, with these differences:

- Each collected generation will have a new `Space`, called "to space". Old
  `Space` for these generations will be called "from space".

- Uncollected generations do not need new spaces. Existing spaces will be used
  to copy new objects to these generations.

- Remembered sets of uncollected generations will be treated as roots.

- **Maintaining remembered sets**: To add an object or field address to the
  remembered sets we use write barriers. Whenever an object is mutated, the write
  barrier (mutation code) adds the object to its generation's remembered set.

- `evac` (the evacuation function) will copy an object in generation `N` to the
  generation `N+1`. When `N` is the oldest generation it will copy it to the to
  space for the current generation.

  When the object is in an uncollected generation, `evac` returns early and
  does not copy the object.

- (No changed needed in `scav`)

- After a GC, from spaces of collected generations will be freed. No changes
  needed in `Space::free`.

That's it! Shouldn't be too difficult once the page allocator is stable.

## (optional) Eager promotion

According to generational hypothesis, new allocations die young, but if an
object survived a few GCs, than it will likely survive many more GCs.

So if a new allocation is pointed by an old object, it makes sense to evacuate
the new allocation to the old generation with the old object, as old object
will keep it alive for many GCs.

Eager promotion can be easily implemented by passing an extra argument for
"target generation" to `evac`. When scavenging a remembered set, pass the
generation number (or reference, pointer) to the generation of the remembered
set. `evac` then copies the current object to the target generation.

Example: if we have 3 generations (`ALLOCATION_SPACE` or 0, 1, 2) and we see an
object in `ALLOCATION_SPACE` when scavenging the remembered set of generation
2, we evacuate the object to generation 2 instead of 1.

I'm not sure how beneficial eager promotion is. In generational copying GCs I
worked on before this was already implemented, so I didn't have the chance to
measure its effectiveness.

## (optional) Aging

According to generational hypothesis, new allocations die young, but maybe not
in exactly one GC. So in some cases it makes sense to collect new allocations
always for a few GCs before promoting to an older generation.

There's an easy way to implement this: just have multiple generations that are
collected always. For example, if we want to collect an object always until it
survives N generations, implement N generations that are collected always. This
is how GHC implements aging.

Alternatively we could store ages in object headers. We current have a few bits
available for this, and aging parameter will be very small (most likely just
2).

Similar to eager promotion, I'm not sure about effectiveness of this idea.

## (optional) Using different collection algorithms

There is an easy way to use an arbitrary collection algorithm for the **oldest
generation**:

- Treat oldest generation remembered set as root. DO NOT collect the oldest
  generation yet.

- When collecting rest of the generations, evacuate live objects to the oldest
  generation.

- Now any objects that are potentially live will be in the oldest generation.
  Collect oldest generation with whatever algorithm you want. (e.g.
  mark-compact)

This is used in GHC's concurrent collector.

In general, when collecting a region of the memory using a moving GC algorithm
(e.g. copying, mark-compact), any pointers to the collect region need to be
updated. That means younger objects will have to be evacuated first to the
generation being collected differently.

However, if we collect the oldest generation using a non-moving algorithm (e.g.
mark-sweep), then we don't need to evacuate all live younger objects to the
oldest generation, as pointers from young to old won't need to be updated. When
we see an object in the oldest generation during evacuation we simply mark it.

**Comment by nomeata** [comment]
Thanks! This is not yet incremental, right, and eventually we need a full, major GC?

Are there designs for incremental GC as well?
