### ISSUE TITLE
Relax the conditions for stable-compatibility

### ISSUE THREAD

**Issue by jzxchiang1** [dfinity/motoko#3047]
Specifically, with respect to this passage in this [document](https://smartcontracts.org/docs/language-guide/upgrades.html):

> The stable-compatible relation is quite conservative. In the future, it may be relaxed to accommodate a change in field mutability and/or abandoning fields from <stab-sig1> (but with a warning).

^ I think abandoning fields would be helpful even without changing field mutability, as it would allow the programmer to add a new field, migrate data from the old field to the new field in a pre-upgrade or post-upgrade hook, and then abandon the new field.

**Comment by luc-blaeser** [comment]
This is implemented now.
