### ISSUE TITLE
Segmentation fault: 11 when trying to define a method which returns a new “instance” of a class

### ISSUE THREAD

**Issue by paulyoung** [dfinity/motoko#3057]
I’m sure I brought this up before but I ran into it again and couldn’t find anything about it.

Here’s a fairly minimal example that reproduces the issue when run with `--check`:

```swift
module {
  public class Id<A>(x : A) {
    public func map<B>(f : A -> B) : Id<B> {
      Id(f(x));
    };
  };
};
```

**Comment by ggreif** [comment]
Heh, if the good old identity functor fails, then all bets are off! ;-)

**Comment by ggreif** [comment]
I bet this is a mutual recursion problem. I have seen OCaml segfaulting when exhausting the stack several times.

**Comment by crusso** [comment]
Interesting...

**Comment by paulyoung** [comment]
If anyone has any suggestions on how to tackle this I can try to take a look.

**Comment by ggreif** [comment]
@paulyoung is this a curiosity problem ("let's code up some Haskell idioms in Motoko") or appearing in your production code?

**Comment by ggreif** [comment]
@nomeata you have squashed "not lazy enough reference" bugs in the past. Maybe this rings a bell?

**Comment by nomeata** [comment]
Not in the typechecker… :-)

**Comment by paulyoung** [comment]
> is this a curiosity problem ("let's code up some Haskell idioms in Motoko") or appearing in your production code?

@ggreif I’m trying to do the former to see if there’s something interesting to write about and perhaps promote Motoko, but bugs like this are preventing me from reaching the latter.

**Comment by ggreif** [comment]
> I think this type should actually be rejected as expansive since it involves polymorphic recursion.

By which definition of _polymorphic recursion_? It would be polymorphic recursion when the type variable (`A` for `B`) were wrapped (nested) in a different type constructor, like `Id<?B>` or `Id<(B, A)>`. But `Id<>` applied to a tyvar isn't polymorphic recursion.
