### ISSUE TITLE
Concern: injectivity of hashing when forming record of stable variables

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#3073]
When serialising stable variables, we pack up each into an option (type `?T`) and form a record with the (hashed) variable names as keys. Do we ever check whether the name hashes are 1:1?

This needs clarification.

Actually, when serialising, it is too late, the check must happen in the type-check phase.

Maybe we implicitly do check this. The desugarer forms a record type, and while at it, I expect that a type invariant would be violated if two names would map to a common hash code. The error message would be rather gross in this case…

Probably worth adding simple test for this. It's possible I forgot, but I would hope the IR checker picks up on this.

**Comment by ggreif** [comment]
We have a check, and its presence is tested:
> test/fail/ok/stability.tc.ok:stability.mo:26.15-26.25: type error [M0019], stable variable names foo and nxnnbkddcv in actor type have colliding hashes

Closing.

**Comment by nomeata** [comment]
Did you add a test?

**Comment by ggreif** [comment]
There was a test already! `test/fail/stability.tc`

**Comment by nomeata** [comment]
Ah, didn’t read your comment carefully, sorry
