### ISSUE TITLE
`languageServer` support for explicit symbol `import`s

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#3078]
#3076 added explicit symbol `import`s to Motoko, but the `languageServer` still ignores them.

Blocks #2354.

**Comment by kritzcreek** [comment]
Unfortunately I don't have an environment with which I can build the compiler at the moment, but I can point you at a couple of places that would need changing and what level of "sophistication" are possible. Also happy to jump on a call some time :)

1. This function needs updating: https://github.com/dfinity/motoko/blob/ecadc8dc6f9318799bbb0dd41591272095778cce/src/languageServer/source_file.ml#L78-L108. The way it's written is from before we had the _shudders_ `parse_module_header` function https://github.com/dfinity/motoko/blob/ecadc8dc6f9318799bbb0dd41591272095778cce/src/mo_frontend/parser.mly#L300
2. For go-to-definition or type-on-hover you can decide if you just want to resolve all unqualified names, or be smarter and try to respect scoping. But you can't rely on the full module being parseable! For example (with `|` representing the users cursor): 
    ```motoko
    import { def } "amodule";

    module {
      let def = 10;
      let x = de|f;
    }
    ```

    The "dumb but robust" thing would be to just resolve `def` according to the import list and have go-to-definition take the user to `amodule` even if that's wrong here. I'd say it's rare enough that users shadow imports that this is valuable even if it produces wrong results occasionally. Otherwise you need an error-recovering parser or for `go-to-definition` to only work on syntactically valid source files.

3. For completions you'll probably have to respect the new more complicated return from `parse_module_header` and handle the unqualified prefix cases accordingly. Right now unqualified names are _always_ completed with respect to the current module, but now you'll also have to consider the explicit imports.
4. If you want to get fancy: For completions we create import edits for the user. You could decide if you want the user to be able to complete the name `filter` even if their import list only says `import { map } from "mo:base/Array";` so far and add `filter` to the import list as an edit on completion.

**Comment by ggreif** [comment]
@kritzcreek Thanks a lot for the detailed answer! Right now this is low-prio, but will want to tackle it as soon as the first user begins to complain! 😉
