### ISSUE TITLE
Namespace in candid imports

### ISSUE THREAD

**Issue by chenyan-dfinity** [dfinity/motoko#3103]
https://forum.dfinity.org/t/motoko-multiple-canister-imports-compile-error/10491

```
import B "canister:B”;
import C "canister:C”;
```

If B and C has the same type variable, one of them will be overwritten in the typing environment.

**Comment by chenyan-dfinity** [comment]
This line is problematic: https://github.com/dfinity/motoko/blob/master/src/mo_idl/idl_to_mo.ml#L66. Either we preprocess the type name before importing or use namespace.

**Comment by crusso** [comment]
I suspect the problem is that idl_to_mo.ml is using a global ref, shared across imports.

**Comment by crusso** [comment]
I'll figure out a repro...

**Comment by crusso** [comment]
Repro here: 
https://github.com/dfinity/motoko/pull/3109
