### ISSUE TITLE
When building `moc` in certain environments the `motoko:compiler` metadata ends up bogus

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#3163]
Specifically our `nix-build perf-delta.nix`, which runs as part of the CI won't assign a reasonable version to `moc`, and thus the metadata ends up as (something akin)
```
motoko:compilerbbf96jzc-myxbz4ai-xvn6cnw3-qsb21pgl
```

I see a few ways out:
- `assert` that this metadata has `.` in it
- warn if no `.` in `motoko:compiler` (suggesting to  build a better compiler)
- suppress `motoko:compiler` when it is not a reasonable version.

I wonder whether other (`nix`-like) build processes also suffer this problem and whether we should include a CI `release`-test that  ensures that `moc --version` is parseable.

**Comment by nomeata** [comment]
It's not really bogus, it's the source hash we have had for a while now. I'd say it works as expected? If someone builds a random commit with nix, this is the best we have.

**Comment by nomeata** [comment]
I'm surprised there is no dash after `compiler` though

**Comment by ggreif** [comment]
because `motoko:compiler` is the name of the section

**Comment by ggreif** [comment]
It is the best we have, but it can produce bad things when bogus metadata hits the replica. There are now checks that examine this section, hopefully they are robust... @ulan

**Comment by ulan** [comment]
Thanks for the heads-up @ggreif. I think it should be okay in the replica code. We only check for the existence of "motoko:compiler" custom section. We don't parse the value of the section (yet).

**Comment by nomeata** [comment]
> because motoko:compiler is the name of the section

Ah, you concatenated name and content in the original message? that explains it.

> It is the best we have, but it can produce bad things when bogus metadata hits the replica. There are now checks that examine this section, hopefully they are robust... @ulan

But it’s not bogus, is it?

Anyways, certainly we on the motoko side don't have to worry about the replica’s parser, that needs to be maximally defensive anyways…

**Comment by ggreif** [comment]
Okay, maybe calling it bogus is my way of transcribing the German "sinnfrei". Anyway, it contains no relevant information for the parsing side.

Yes, the parser will have to see that this is not a version and bail out. But its will know that the presence of this section means a lower bound on `moc`'s version. So it has that.

Let's hope that not too many bootleg `moc`s come in circulation :-)

Closing. This was just a documentation attempt of a weird string I found in `wasm2wat` output that I couldn't immediately make sense of.

**Comment by nomeata** [comment]
We could make it more useful if we commit to the repo the _last_ released version number as part of the release process and then use `1.2.3+sndjhenendj` as the version string. This makes it clear that it is a custom build, but still gives some approximate version number.

**Comment by ggreif** [comment]
We have that already (see the top of `Changelog.md`).

**Comment by nomeata** [comment]
Oh good point! Can you open an issue (on the phone right now)? I might give it a shot at some point
