### ISSUE TITLE
Enhancement: dynamic compatibility check in postupgrade

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3199]
Now that we got access to a runtime candid subtype check (#3171), we could consider using it to perform a dynamic and atomic (!) type safety check on upgrade. 

By storing the candid interface in the stable variable blob as an extra type table entry at a known offset (0 springs to mind), the postupgrade method could consult the previous interface stored in stable memory to test compatibility with the new interface, trapping if incompatible.

That would allow the upgrade to fail and rollback on incompatibility, avoiding the current [time-of-check/time-of-use hazard ](https://en.wikipedia.org/wiki/Time-of-check_to_time-of-use) in the static check implemented by dfx.

By extending the runtime candid subtype check to deal with `alias` idl types (invariant, mutable types) we could also extend the dynamic check to stable variables (we currently omit candid subtype tests when deserializing stable variables, blindly trusting the static check is still valid). The checks could be performed during de-serialization or in bulk prior to deserialization.

NB: we'd need to rev the stable variable format version to make this work so that we can tell the upgraded canister carries the necessary interface description in type table entry 0.

A side benefit of this approach is that it would make it easier to type any actor class upgrade facilities, allowing us to rely on the dynamic check instead of enhancing the type system.

A downside of this approach is that we might want some way to suppress the check for deliberate breaking changes (e.g. during development) or in production (when the canister is perhaps known to have no existing clients.) A compile or prim based run-time flag might suffice for this, causing the postupgrade to abort when  the check failed and the flag remains clear.
 
@chenyan-dfinity @nomeata @rossberg whaddya think?

**Comment by chenyan-dfinity** [comment]
> we could consider using it to perform a dynamic and atomic (!) type safety check on upgrade.

Do we plan to allow upgrade to run across multiple messages? If so, we cannot make it atomic in the future.

I think static check has its value, mainly giving more user-friendly error messages when the check fails. Dynamic check is more atomic and provides another layer of safety guarantee.

> A side benefit of this approach is that it would make it easier to type any actor class upgrade facilities, allowing us to rely on the dynamic check instead of enhancing the type system.

Not sure what you mean by type actor class upgrade.

**Comment by nomeata** [comment]
Ah, now I get it, this is foremost about the public interface, not the stable memory interface. I was thick on Signal…

I'd say an override flag is a must. As you say, not all canisters need that high level of forward compatibility. Not sure if it should be a flag passed to the canister (tricky, because we already use all of the canister init arg for the source-visible class parameters) or a compile time flag (easier, but somewhat wrong, as it isn't really a property of the module per se, but of the particular deployment).

Otherwise I'm at “shrug, why not”.

**Comment by crusso** [comment]
> > we could consider using it to perform a dynamic and atomic (!) type safety check on upgrade.
> 
> Do we plan to allow upgrade to run across multiple messages? If so, we cannot make it atomic in the future.
If you mean via DTS (deterministic time slicing) then the entire upgrade will still be atomic, even if it spans multiple rounds. At least, in understanding of DTS.

> I think static check has its value, mainly giving more user-friendly error messages when the check fails. Dynamic check is more atomic and provides another layer of safety guarantee.

Right, I don't propose we get rid of the static check. It's still useful and easier to make user-friendly with error messages.

> > A side benefit of this approach is that it would make it easier to type any actor class upgrade facilities, allowing us to rely on the dynamic check instead of enhancing the type system.
> 
> Not sure what you mean by type actor class upgrade.

I mean that if we provide ways to upgrade installed actor classes through language support, then we can safely punt some of the static checking we were considering to run-time checking, without having to innovate at the Motoko type level (e.g. by adorning actors with their stable variable signatures so we can statically check upgrades.)

**Comment by rossberg** [comment]
I like this. :)

**Comment by crusso** [comment]
> I like this. :)

Seriously? I never thought I'd see you approving of a dynamic check ;->
