### ISSUE TITLE
When compiling, the specified parameters --actor-idl do not work

### ISSUE THREAD

**Issue by wusualis** [dfinity/motoko#3233]
When compiling, the specified parameters --actor-idl do not work. 

See as the following command :
`moc ./motoko_test.mo -o /motoko_test/.dfx/local/canisters/motoko_test/motoko_test.wasm -c --debug --idl --stable-types --public-metadata candid:service --actor-idl /motoko_test/.dfx/local/canisters/idl/ --actor-alias motoko_test r7inp-6aaaa-aaaaa-aaabq-cai --package base $HOME/.cache/dfinity/versions/0.9.2/base`

The *.did file still in directory `/motoko_test/.dfx/local/canisters/motoko_test/` as *.wasm in.

**Comment by nomeata** [comment]
Thanks for your report. I don’t fully understand the report, though. The `--actor-idl` flag tells `moc` where to _look_ for existing `.did` files for imported canisters; it will not affect the output path for the _generated_ `.did` file. Is that part of the confusion?

**Comment by wusualis** [comment]
OK, got it. It's a misunderstand about it.
When i use 
`import * "ic:r7inp-6aaaa-aaaaa-aaabq-cai"`
i need to copy that `*.did` file to `idl` directory.
So i want to do that copy operation in command automatically.
Anyway, thx a lot.

**Comment by nomeata** [comment]
Yes, the assumption is that a tool like `dfx` takes care of that, not `moc` itself. 

Ok if I close this?

**Comment by wusualis** [comment]
> Yes, the assumption is that a tool like `dfx` takes care of that, not `moc` itself.
> 
> Ok if I close this?



OK. :)
