### ISSUE TITLE
library: performance counters and how to expose them

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3294]
#3288 exposes the raw ic0.performence_counter as a prim.

`ic0.performance_counter(type)`  is reset to zero on every context switch (IC entry point) which means you cannot correctly use it, e.g. across awaits, without more work possibly compiler support. What's worse, the counter isn't updated within basic blocks though any reasonable stretch of Motoko code is probably unlikely to observe that.

 Instead of, or in addition to, exposing the raw prim in base, shall we just/also expose a higher-order function, perhaps:

```
measure: (counter_type: Nat32) -> (<A,B>((fun : A -> B) -> ( (arg:A) -> (B, Nat64)))
```

eg.

`let (i, diff) = measure(0)(fib)(1000)`

Since (local) functions can't await, this might prevent some confusion due to the IC semantics of ` performance_counter.`

My one concern is that Motoko functions aren't unary-2-unary, so some plumbing may be required even in common cases (e.g. for binary functions).

The other option might be:

```
measure: (counter_type: Nat32) -> (thunk:() -> ()) -> Nat64
```

So users are forced to thunk their computations and just get a measurement, with no result.

I'm once again regretting that we went for n-ary function types in Motoko (and that I pushed for them)

**Comment by chenyan-dfinity** [comment]
Thunk is general enough, e.g., `f(x,y) --> func () { ignore f(x,y) }`

**Comment by matthewhammer** [comment]
What does the argument `counter_type: Nat32` do?  (Looked at the files changed in https://github.com/dfinity/motoko/pull/3288 but I didn't see it documented there.)

**Comment by crusso** [comment]
Landed here:
https://github.com/dfinity/motoko-base/pull/381
