### ISSUE TITLE
What is the `release` branch for?

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#3312]
When looking at  `Building.md` it seems that the only purpose of the `release` branch is to push Motoko labels.

But we could do that for master too, or just `git push --tag`.

I am asking because `release` seems to have received a stray commit, and I can't repair the situation. Everything else seems to work, so maybe we can sunset the `release` branch.

**Comment by nomeata** [comment]
Isn't this the branch that ask pulls from (via niv update)? Or maybe that is no longer the case? Then it can be removed.

**Comment by ggreif** [comment]
It appears that the bots open branches like `update/ic-0a620a8bcf8267266d83dd1a3bafd0cf745edfc0` for `niv update`. See #3311.

**Comment by crusso** [comment]
From Building.md

"The `release` branch should thus always reference the latest release commit."

Perhaps that's the only function the release branch was serving...

**Comment by nomeata** [comment]
I’m talking about the updates in the sdk repo, not our updates.

> Perhaps that's the only function the release branch was serving...

But I see that https://github.com/dfinity/sdk/blob/master/nix/sources.json no longer pulls in the `release` branch, but the tarballs on the github releases. So yes, the `release` branch can go.
