### ISSUE TITLE
"do {}" blocks should be allowed as a part of an expression

### ISSUE THREAD

**Issue by mikhail-turilin-dfinity** [dfinity/motoko#3316]
In the following example function "number2" doesn't compile and it's not clear why.

```
   public query func number1() : async Nat {
    let x = 40; let y = 2;
    x+y
  };
  
  public query func number2() : async Nat {
    let x = 40; let y = 2;
    x + y + do {
      let x = 1;
      let y = x + 1;
      x * y + x
    } + x + y
  };

  public query func number3() : async Nat {
    let x = 40; let y = 2;
    do {
      let x = 1;
      let y = x + 1;
      x * y + x
    }
  };
```

**Comment by crusso** [comment]
https://internetcomputer.org/docs/current/developer-docs/build/languages/motoko/basic-concepts#from-declarations-to-block-expressions might be a good place to add this (at the end)

**Comment by crusso** [comment]
Fixed in doc branch here https://github.com/dfinity/motoko/pull/3172/commits/5c99f088131338854d413cecbf072ba4479cb426
@mikhail-turilin-dfinity

**Comment by crusso** [comment]
(This will propagate to the web the next time the portal team does a sync)
