### ISSUE TITLE
Optimise Motoko Assignment

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#3402]
I have just encountered such compiled code:
``` wasm
    …
    call $compute
    local.set $new_val
    i32.const 65727      // destination mutcell
    local.get $new_val
    i32.store offset=5
```
Should be (when destination is not side-effecting!)
``` wasm
    i32.const 65727      // destination mutcell
    …
    call $compute
    i32.store offset=5
```

Source is
``` Motoko
object a {
    var v = 42;
    public func incr() = v += 1
};
```

I think mutable object access (`DotLE`) is (almost) never side-effecting in Motoko, as folks seldom write stuff like
``` Motoko
var foo = 0;
{ var a = do {foo := 7; 9} }.a += 1;
```

**Comment by nomeata** [comment]
Even when the destination is sideeffecting it would be reasonable to calculate the destination first, and then the value, and then invoke `store`.

**Comment by nomeata** [comment]
Ah, simple, just make a local change here

https://github.com/dfinity/motoko/blob/f325002a4d10a172d96a317d8e00bd7a9cb41478/src/codegen/compile.ml#L6768-L6772

**Comment by nomeata** [comment]
This comes from

https://github.com/dfinity/motoko/blob/f325002a4d10a172d96a317d8e00bd7a9cb41478/src/codegen/compile.ml#L6768-L6772

and `set_val` expects the value on the stack.

Could be fixed if `set_val` returns some `pre_code` and some `post_code` instead.

**Comment by nomeata** [comment]
https://github.com/dfinity/motoko/blob/f325002a4d10a172d96a317d8e00bd7a9cb41478/src/codegen/compile.ml#L8143-L8145

`compile_lexp` is already set up to use that pattern, so I don’t see problems pushing that pattern through to `set_val`.
