### ISSUE TITLE
IDE can support multiple canisters

### ISSUE THREAD

**Issue by hansl** [dfinity/motoko#3473]
Reported by @kritzcreek 

# Resolving canister aliases in the IDE

Problems:

At this point in time the Language Server (called LS going forwards)  uses the same set of arguments as moc, meaning all canister aliases  have to be given statically on startup, and all `.did` files have to  be put into the same directory for the LS to find them

When the LS starts up `.did` files might not have been generated and  the canister ids for canisters in the project might not be known yet.

DFX generates temporary files during the build process that the  long-running LS can't read.

This means currently the LS doesn't work well in multi-canister  projects (It doesn't work for any canister that imports another one)

Solution 1:

DFX outputs the required information for the LS to a known location  in a persistent fashion. This would include:

canister alias - entry point mapping

canister alias - id mapping

a single path where all IDL files get generated (and garbage collected!)The two canister alias mappings can be used to invalidate out of dateIDL files from the LS, which can then produce more up-to-dateversions on the file system, or update them in-memory.The garbage collected bit is important because the LS can't tell whichidl files are for external services and which are for canisters thatused to exist in the local project but have been removed by the usersince.

Solution 2:

The LS reproduces enough of DFX's understanding of a project to be  able to handle the dynamic IDL generation on its own

This means moving more knowledge about what a Motoko project is  into the compiler, so would need design work

**Comment by rvanasa** [comment]
Resolved by a combination of https://github.com/dfinity/sdk/pull/2375 and https://github.com/dfinity/vscode-motoko/pull/64.
