### ISSUE TITLE
Collecting core dumps on GitHub Ubuntu build server

### ISSUE THREAD

**Issue by luc-blaeser** [dfinity/motoko#3579]
I am encountering sporadic segmentation faults on drun on the GitHub Ubuntu build server, e.g. [8cf3766](https://github.com/dfinity/motoko/pull/3562/commits/8cf37660ef87eaab51c183535e64666a4ceea04e). It is unrelated to the latest GC changes as it also occurs on a simple master branch.

I wonder how I could collect core dumps under the Ubuntu build server. I currently try to locate them in the following directories (after activating core dumps with `ulimit -c unlimited`):

```
/var/lib/systemd/coredump
/var/crash
/var/lib/apport/coredump
```

Maybe there are more potential locations? Or am I missing something?

@nomeata: Claudio suggested to also ask you whether you maybe have experience in collecting core dumps from the build server?

Thank you very much,
Luc

**Comment by nomeata** [comment]
It’s built by `nix` in a sandbox, so I would not expect any files anywhere after a build… It will be hairy to get that out from both nix and Github Actions.

Nobody managed to reproduced it locally yet?

**Comment by luc-blaeser** [comment]
Thanks a lot. In meantime, I was able to collect the core dump (with a textual hex dump).
