### ISSUE TITLE
bug: inconsistent definition of static expressions in imported modules

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3585]
@timohanke reasonably asks:
Why is

Field.mo
```
module {
  var n = 0; // rejected, non-static
}
```
not allowed but

Record.mo
```
module {
  let x = { var n = 0 }; // allowed, static?
}
```
is allowed when imported as a library:

```
import F = "FIeld";
import R = "Record";
import O = "Object";
actor {
}

We should either rule out or allow both, I'd say, but which? For purity, I'd say rule them both out, but our own libraries like ExperimentalStableMemory are actually stateful (at least for now).

Curiously:

Object.mo
```
module {
  let x = object { var n = 0 }; // rejected, non-static
}
```
is not allowed!

https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=1172251413

**Comment by nomeata** [comment]
I'd disallow objects in modules. Either it's stateful, and we don't want it, or it's a stateless, and could be a module.

(Or get rid of modules anyways and it's all just objects)

**Comment by crusso** [comment]
Maybe, but we should also rule out var field in records, which are different syntactically from objects in the motoko AST.

**Comment by matthewhammer** [comment]
> Maybe, but we should also rule out var field in records, which are different syntactically from objects in the motoko AST.

Yep, a module's definition of public values should not require allocating any mutable memory, period.  If it does that, it's not static.  That it is allowed is a bug.
