### ISSUE TITLE
Generate usage examples for the base library and Vessel packages

### ISSUE THREAD

**Issue by rvanasa** [dfinity/motoko#3611]
Here are a few alternate approaches:
1. Create example stubs based on type definitions (e.g. `Array.sort<Nat>([0], func (a, b) { #equal })`). Although this would only work in certain cases without modifying the inputs, it could be helpful for those who are confused by the type definition syntax. 
2. Design a web interface for running examples (similar to Candid UI), ideally as part of a more general standalone learning tool.
3. Introduce a syntax or doc comment convention which could be used for both examples and unit tests. 
4. Manually write a lot more examples in the base library using Markdown in doc comments.

(2) or (3) would probably work best for a Q1 timeline, while (4) seems the most practical for the remainder of Q4. 

We could also combine (1) and (4) to generate and then manually adjust examples for most of the base library functions. 

Initial progress: #3610

Thoughts?

**Comment by krpeacock** [comment]
One niche that I'd like to see covered is an examples of how to convert among different types and structures. A common example would be `Array -> Buffer -> Array` now that concatenation is deprecated

**Comment by rvanasa** [comment]
Closing in light of all the recent base library documentation improvements.
