### ISSUE TITLE
RFC: share blob, text and Nat/Int values in stable format

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3620]
(Inspired by https://forum.dfinity.org/t/heap-out-of-bounds-use-motoko/10497/17?u=claudio)

The stable format ("Candidish") preserves some sharing, but only for mutable fields and arrays, where it's absolutely necessary to preserve identity. Due to subtyping and the type-directed nature of candid serialization, it's not possible to extend this to compound types (since one static view of a value doesn't reflect all the static properties of its aliases). However, I think it would be relatively easy and safe to extend the current mechanism for mutable fields and arrays to preserve sharing of  heap allocated blob, text, and, if desirable, (large) nat/int values. That might mitigate, some, but not all, of the space cost of flattening graphs of immutable values to trees, as we do currently.

The scenario in the post involved lots of token ledger data, with non-trivial 32-byte blobs used to identify accounts in transaction records and other blob indexed maps with shared domains. Another scenario might be a collection of large blob slices (think video fragments) over the same underlying blob. 

Only to be considered after merging the candid sub-type check PR, since this involves changing type descriptors/type table entries for the primitive types in question (using type descriptor `alias`) in the extended serialization format.

More of a band-aid than a proper fix.

**Comment by nomeata** [comment]
> nat/int values

We'd need to double check that that's safe if we alias the same value at different (non-stop) types.

**Comment by nomeata** [comment]
> since this involves changing type descriptors/type table entries for the primitive types in question (using type descriptor alias) in the extended serialization format.

Maybe not needed if we apply this consistently

**Comment by crusso** [comment]
Well, I was hoping this would be backwards compatible even if we don't apply it consistently. We would read old unshared atomic values as before from old versions, but produce aliases going forward. We do have version number in the stable format which we can bump to prevent upgrade from code generated with the new compiler from code generated with old compiler. Fingers crossed and all that.

**Comment by nomeata** [comment]
> Well, I was hoping this would be backwards compatible even if we don't apply it consistently. 

If we use `alias` in the type table, as you propose, I think that’s true.

**Comment by crusso** [comment]
> > nat/int values
> 
> We'd need to double check that that's safe if we alias the same value at different (non-stop) types.

non-top, you mean. I'm pretty sure this is ok. The only non-trivial one is Nat <: Int, but the representations are compatible with no loss of info in the supertype, so can this possibly hurt? But good to think about it.

**Comment by nomeata** [comment]
The decoder would have to be prepared to accept a value with an int in the type table, if the shared value gets serialized at value int first? If it even works (remember that int and nat have different representations in candid)

**Comment by crusso** [comment]
I didn't know they were differnt in candid - just to save 1 bit? I guess we can just skip bignums.

**Comment by nomeata** [comment]
```
M(n : nat)      = leb128(n)
M(i : int)      = sleb128(i)
```

**Comment by luc-blaeser** [comment]
Superseded by enhanced orthogonal persistence.
