### ISSUE TITLE
Typo await should be await*

### ISSUE THREAD

**Issue by timohanke** [dfinity/motoko#3636]
https://github.com/dfinity/motoko/blob/c8c0917052eda95669dabd612834d66cba5a19ec/doc/md/language-manual.md?plain=1#L2249

Should this be "Expression `await* <exp>` evaluates ..."?
And a newline before the paragraph?

**Comment by timohanke** [comment]
And in the subsequent sentences
"If r is trap, evaluation returns trap. Otherwise r is a delayed computation"
we only know if it is a trap when the computation is attempted, or? The word "otherwise" is confusing.

**Comment by crusso** [comment]
> https://github.com/dfinity/motoko/blob/c8c0917052eda95669dabd612834d66cba5a19ec/doc/md/language-manual.md?plain=1#L2249
> 
> Should this be "Expression `await* <exp>` evaluates ..."? And a newline before the paragraph?

Probably, yes. I'll fix it.

> And in the subsequent sentences "If r is trap, evaluation returns trap. Otherwise r is a delayed computation" we only know if it is a trap when the computation is attempted, or? The word "otherwise" is confusing.

No, I think that's ok.
```  
await* (if rand() { Debug.trap "ohoh"} else f())
```
would be an example of immediately trapping, before evaluating the delayed compuation.

**Comment by crusso** [comment]
Thanks for the reports!

**Comment by timohanke** [comment]
I don't understand the example of immediate trapping. Why does it trap immediately, what are the expressions that do!
