### ISSUE TITLE
Unusual `nan` (not a number) floating point representation with a negative sign on `wasmtime`.

### ISSUE THREAD

**Issue by luc-blaeser** [dfinity/motoko#3647]
**Update**: Only related to the `wasmtime` compilation:
It seems that `nan` ("not a number" of the floating point type) is always represented and interpreted with a negative sign, which is unusual.

This may lead to the following behavior that differs to other programming languages implementing IEEE 754:
```
let NaN = 0.0/0.0;
Prim.debugPrint(debug_show(NaN));
Prim.debugPrint(debug_show(Prim.floatCopySign(1.0, NaN)));
```

Output:
```
-nan
-1.000000
```

**Comment by luc-blaeser** [comment]
Good question: 
This inconsistency only happens with `wasmtime`
It is correct with `drun` and the interpreter.

**Comment by crusso** [comment]
Interesting. One difference between drun and wasmtime, is that the replica does some normalization (or at least used to) on floating point operations by rewriting the wasm. That step won't happen when running on wasmtime, unless there's something I'm not aware of (@nomeata)

**Comment by chenyan-dfinity** [comment]
I think the normalization is a flag to `wasmtime`, not rewriting the Wasm: https://github.com/dfinity/ic/tree/master/rs/embedders#nondeterminism. We can try running wasmtime with that flag enabled.

**Comment by luc-blaeser** [comment]
We need to activate NaN canonicalization for wasmtime used in the base tests.
`wasmtime --enable-cranelift-nan-canonicalization <MODULE>`

With this, the NaN result of operations consistently has a positive sign bit except for `copySign` and `neg` that can result negative NaN. This is in line with the Wasm specification that only requires NaN sign bit to be propagated on `fabs`, `fneg`, and `fcopysign`.

**Comment by luc-blaeser** [comment]
Fixed by https://github.com/dfinity/motoko-base/pull/586

**Comment by luc-blaeser** [comment]
Also fixed by https://github.com/dfinity/motoko/pull/4175
