### ISSUE TITLE
bug: [mo-doc] the md output doesn't document a class constructor as a function, just the class itself.

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3721]
For an example, see Random.mo

![image](https://user-images.githubusercontent.com/85788/214266271-53a42069-5abe-4f99-a3aa-e42f40fa0d9c.png)

There should probably be an entry for the constructor *function* Finite(b : Blob) -> Finite.

**Comment by crusso** [comment]
This might already be done properly for adoc and html output, but never got implement for md.

**Comment by rvanasa** [comment]
Good point! I'll take a look at this.
