### ISSUE TITLE
Variant tag and reserved words

### ISSUE THREAD

**Issue by Gekctek** [dfinity/motoko#3776]
Is it intended to have variant tags not be able to use reserved words.
Currently I have the following escaped with `_`
#_null
#_func
#_type
#_query
Thoughts on alternatives or is it possible to have anything after the `#` not parse to reserved words?

**Comment by nomeata** [comment]
It was suggested that Motoko gets support for raw identifiers like https://doc.rust-lang.org/rust-by-example/compatibility/raw_identifiers.html. it seems inevitable in a language where names become part of the interface

**Comment by rvanasa** [comment]
I recently learned that this is possible (at least for Candid serialization) using keywords such as `null_` or `func_`. 

Example via the [motoko npm package](https://www.npmjs.com/package/motoko):

[![image](https://user-images.githubusercontent.com/522097/216833431-38c3cf46-a994-4bf1-bd6e-372b7e2a75cc.png)](https://runkit.com/embed/iopepuwaktey)

**Comment by chenyan-dfinity** [comment]
Eventually we need raw identifier. For now, we can follow the Candid-Motoko spec to append `_` in the identifier if the identifier is a reserved keyword. See the `unescape` and `escape` function in the spec: https://github.com/dfinity/motoko/blob/master/design/IDL-Motoko.md

**Comment by nomeata** [comment]
Oh, right, I forgot that we defined a mapping that allows you to encode these names: https://github.com/dfinity/motoko/blob/master/design/IDL-Motoko.md#type-name-mangling

**Comment by Gekctek** [comment]
So close, just put it on the wrong side lol. Perfect, thank you
