### ISSUE TITLE
Separate runtimes for different GC strategies

### ISSUE THREAD

**Issue by ggreif** [dfinity/motoko#3795]
Right now we have a release and a debug build o the RTS:
```
rts/mo-rts-debug.wasm
rts/mo-rts.wasm
```
these can be selected individually by giving flags to the `moc` build.

I propose to have 4 release builds, which contain the relevant GC strategy (only):
- copying
- compacting
- generational
- incremental

I do not care about the debug build being too big.

**Comment by nomeata** [comment]
Is it worth it?

**Comment by luc-blaeser** [comment]
https://github.com/dfinity/motoko/pull/3913 is an implementation that separates the (future) incremental GC from the non-incremental GC builds. This is because the incremental GC extends the object header to store an additional forwarding pointer that is not needed for the other GCs.

**Comment by luc-blaeser** [comment]
This is mostly realized in current implementation
