### ISSUE TITLE
Docs: should actor subtyping be mentioned in the Quick Reference?

### ISSUE THREAD

**Issue by Web3NL** [dfinity/motoko#3846]
There is no mention of actor subtyping [in the quick ref](https://internetcomputer.org/docs/current/motoko/main/language-manual#subtyping) 

But @rossberg [clearly states](https://forum.dfinity.org/t/using-variant-variables-in-the-canister-public-interface-return-value-breaks-composability/16960/19?u=samer) that subtyping behaves the same as objects

**Comment by crusso** [comment]
Sort of. The document states:
![image](https://user-images.githubusercontent.com/85788/221680518-f5ae1514-5c65-4e95-a2ab-11c69a61b85b.png)
so it is actually  handled by the special case `<sort0> = <sort1> = actor`.
However, reading that spec, I see I screwed up in the field relationship. It's meant to read that every field in fts1 (of U) has an appropriate field in fts0, not the other way around. 
I'll fix that and clarify that the clause covers all object like types (ie. object, actors and modules).
Thanks for pointing this out!
