### ISSUE TITLE
perf: optimize object layout to save one word

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3851]
In compile.ml, module Object, we see that the object layout stores `n_fields`, the field count, in the object itself, but I think this could be stored at one remove in the mini-table describing the fields, saving one word per object instance. The field_hash array is shared amongst multiple instances).

```
    ┌──────┬─────┬──────────┬──────────┬─────────┬─────────────┬───┐
    │ obj header │ n_fields │ hash_ptr │ ind_ptr │ field2_data │ … │
    └──────┴─────┴──────────┴┬─────────┴┬────────┴─────────────┴───┘
         ┌───────────────────┘          │
         │   ┌──────────────────────────┘
         │   ↓
         │  ╶─┬────────┬─────────────┐
         │    │ ObjInd │ field1_data │
         ↓    └────────┴─────────────┘
        ╶─┬─────────────┬─────────────┬───┐
          │ field1_hash │ field2_hash │ … │
          └─────────────┴─────────────┴───┘


```
i.e. we move to this layout (excuse my broken ASCII art)

```
           ┌──────┬─────┬──────────┬──────────┬─────────────┬───┐
           │ obj header │ hash_ptr │  ind_ptr │ field2_data │ … │
           └──────┴─────┴────┬─────┴┬─────────┴─────────────┴───┘
         ┌───────────────────┘      │
         │   ┌──────────────────────┘
         │   ↓
         │  ╶─┬────────┬─────────────┐
         │    │ ObjInd │ field1_data │
         ↓    └────────┴─────────────┘
        ╶─┬─────────────┬─────────────┬─────────────────┐
          │ n_fields    │ field1_hash │ field2_hash │ … │
          └─────────────┴─────────────┴─────────────────┘


```

**Comment by rossberg** [comment]
With a bit more cleverness you might also be able to merge header and hash_ptr into a single slot that is either an integer tag or a pointer to an object descriptor, probably with one bit reserved to distinguish the two, and another for marking.

**Comment by crusso** [comment]
> With a bit more cleverness you might also be able to merge header and hash_ptr into a single slot that is either an integer tag or a pointer to an object descriptor, probably with one bit reserved to distinguish the two, and another for marking.

I think that might not work well with our compacting/generational gc that does threading via the tag word (and relies on there only being  a small number of tag values), but could work well with the incremental GC. But I could be misremembering.

**Comment by luc-blaeser** [comment]
Interesting idea. It is true that the tag is temporarily changed by the pointer threading technique during the compacting and generational GC. But the tag is restored (as would be the pointer to the object descriptor stored at that place) and the tag is not accessed while it is invalid. So, probably, it would work.

**Comment by nomeata** [comment]
I wonder why we put it in the object itself originally, I think we knew that we could make the proposed change. Maybe to avoid the extra indirection in GC? But besides that I see no good reason not do.

> With a bit more cleverness you might also be able to merge header and hash_ptr into a single slot that is either an integer tag or a pointer to an object descriptor, probably with one bit reserved to distinguish the two, and another for marking.

Sounds like an variant of the idea of putting array or object lengths in the first word somehow. I believe we have an issue for that discussion, but I can never find it.

**Comment by rossberg** [comment]
You never want to put array lengths in the descriptor, however, because that size is not invariant with the type. I.e., you would need to allocate in the order of one descriptor per value instead of one per type, which would use _more_ space than having it in the value directly.

**Comment by luc-blaeser** [comment]
Implemented with enhanced orthogonal persistence
