### ISSUE TITLE
Trapping with a date string removes the offset

### ISSUE THREAD

**Issue by Gekctek** [dfinity/motoko#3854]
Ran into a very weird bug where if there is a datetime in a string value that is being used in a trap, it will remove the tz offset. Took me a long time to figure this out. Seems like Debug.print is fine though
```
Debug.trap("2022-11-21T21:30:42-05:00");
```
Will output `2022-11-21T21:30:42`

**Comment by nomeata** [comment]
Where do you see the output? In a message from the Internet Computer?

Is it really the dash, or not just the string length?

I cannot reproduce it here in a simulated run in `drun` or `ic-ref-run`, so it is more likely an issue with the Internet Computer:
```
ingress Completed: Reply: 0x4449444c016c01b3c4b1f204680100010a00000000000000000101
ingress Err: IC0503: Canister rwlgt-iiaaa-aaaaa-aaaaa-cai trapped explicitly: 2022-11-21T21:30:42-05:00
```

**Comment by Gekctek** [comment]
Interesting. I'm using the MOPS testing library which relies on dfx. I'll investigate and put an issue on the other repo. 
I tried some variations that weren't datetimes with a tz offset and they were fine. It's like something parses it as a date but outputs it without the offest. 
My case was actually a date nested deep in an object that i outputted via debug_show, so it doesn't seem like a length issue
