### ISSUE TITLE
let-else: `()` cannot produce expected type `None`

### ISSUE THREAD

**Issue by di-wu** [dfinity/motoko#3864]
> src/oops.mo
```motoko
func oops() : Nat {
  var x = 0;
  loop {
    if (x >= 10) return let y = x else {
      x += 1;
    }
  };
};

assert(oops() == 10);
```
Works in `moc v0.8.2`, breaks in `moc v0.8.3` (`moc -r src/oops.mo`).

**Comment by ggreif** [comment]
Yes, `let` can have an `else` control flow now, whereas in 0.8.2 that belonged to the `if`.
Looks like a contrived example, but if you really want it that way, just make it `return {let y = x} else ...`.

**Comment by di-wu** [comment]
Yes, there are easy workarounds, I just did not expect things to break after upgrading.
It this is expected, then I'll close this.

**Comment by ggreif** [comment]
Claudio came up with a neat fix that unbreaks your code. #3869 will be part of the 0.8.4 release.
