### ISSUE TITLE
bug: possible miscompilation of switch in 0.8.4

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#3887]
Example code:

```
 import Prim "mo:⛔";
 
 actor {
   func f() {};
 
   func g(name : Text) : () -> () {
     switch (name) {
       case "some" f;
       case _ Prim.trap("Not found");
     };
   };
 
   public func init(name : Text) {
     g(name)();
   };
 };
```

Using a return keyword fixes it:

```
      case ("some") return f;
```

There is a difference between 'case ("some") f;' and 'case ("some") return f; '  (for 0.8.4).

The error message is "Canister v32cj-3iaaa-aaaaa-aaa2a-cai violated contract: function invocation does not match its signature". Does that mean that without the return keyword it tries to invoke f instead of returning f?

Reported by @timohanke  fyi @nomeata

**Comment by crusso** [comment]
I can reproduce the behaviour

https://m7sm4-2iaaa-aaaab-qabra-cai.ic0.app/?tag=1621584345

**Comment by ggreif** [comment]
Happens with `if` analogously:
``` Motoko
if (name == "some") f else Prim.trap("Not found");
```

**Comment by nomeata** [comment]
This might be confusion in the backend if a const thing meets a `None` thing. Let me see.

**Comment by nomeata** [comment]
Can reproduce in `drun`. Very weird, stuff like existence of unrelated public method make a difference. Maybe some confusion with table indices.

**Comment by nomeata** [comment]
Here is a reproducer using `wasmtime`:
```
import Prim "mo:⛔";
func f() {};
func g() : () -> () {
  if (true) f else Prim.trap("Not found");
};
func go1() { g()(); };
go1();
```

Incidentially, the problem goes away on master, due to b0230e41f2a0c8de568a262ed7d83bee12581235 in particular.

So we could consider this fixed if we want :-)

**Comment by ggreif** [comment]
That's great, I'll prepare a regression test from this.

**Comment by nomeata** [comment]
Here is the effect of that commit, as per
```
./compare-wat.sh -f b0230e41f2a0c8de568a262ed7d83bee12581235^ -t b0230e41f2a0c8de568a262ed7d83bee12581235 run/issue3887.mo
```
(a useful tool!)
```diff
   (func $g (type 14) (param $clos i32) (param $b i32) (result i32)
     local.get $b
-    if  ;; label = @1
+    if (result i32)  ;; label = @1
+      i32.const 2097287
     else
       i32.const 2097267
       call $blob_of_text
       call $as_ptr_size
       global.get 17
       global.get 18
       call 31
       unreachable
-    end
-    i32.const 0)
+    end)
```

I should stare at the code if my change really fixes the problem, or just made it disappear in this case.

**Comment by nomeata** [comment]
Found it. The following code reproduces it on `master`:
```
import Prim "mo:⛔";
func f() : () {};
(if (true) f else Prim.trap("Not found"))();
```
And this is the fix:
```diff
@@ -9504,7 +9511,7 @@ and compile_prim_invocation (env : E.t) ae p es at =
     IC.performance_counter env

   | OtherPrim "trap", [e] ->
-    SR.unit,
+    SR.Unreachable,
     compile_exp_vanilla env ae e ^^
     IC.trap_text env
```
PR coming up.
