### ISSUE TITLE
I can't install using Nix

### ISSUE THREAD

**Issue by vporton** [dfinity/motoko#4151]
Following the instructions at https://github.com/dfinity/motoko/blob/master/Building.md I get:

```
$  nix-env -i -f . -A moc
error: attribute 'moc' in selection path 'moc' not found
```

**Comment by crusso** [comment]
Hmm, does 'nix-shell' work for you?

**Comment by nomeata** [comment]
Works for me here with the latest checkout.

Which directory do you run the command in? You have to check out the `motoko` repository:
```
~/dfinity/motoko $ nix-env -i -f . -A moc
installing 'moc'
building '/nix/store/xjd6assa1h1g9wp6fan1mglff1hbyqyy-user-environment.drv'...
~/dfinity/motoko $ nix-env -e moc
uninstalling 'moc'
```

**Comment by vporton** [comment]
> You have to check out the `motoko` repository and run the command therein

You should mention this in the `Building.md` file, because otherwise `nix-env` looks like a generic installer such as `apt`, `yum`, `brew` that downloads from Internet and installs no matter in which directory it is run. It is really confusing.

**Comment by nomeata** [comment]
Good idea: https://github.com/dfinity/motoko/pull/4153

(The `Building.md` is more aimed at developers, as endusers should get `moc` via `dfx`, but that shouldn’t stop us from improving the instructions.)
