### ISSUE TITLE
Bug: Principal.fromBlob accepts blobs larger than 29 bytes

### ISSUE THREAD

**Issue by crusso** [dfinity/motoko#4267]
This is problematic because candid principal deserialization rejects principals with more than 29 bytes, leading to failed upgrades.

We should either prevent creation of large principles, a (minor?) breaking change, or, perhaps, allow larger principals for stable variable deserialization and (maybe also) Candid deserialization.

See

https://forum.dfinity.org/t/when-upgrading-code-or-deployment-an-error-message-is-reported-and-the-error-message-is-vague/24392/15

(Candid does not actually limit principal sizes but the IC does)

**Comment by nomeata** [comment]
I'd say that the “principal” in candid refers to the principal as defined by the public spec, and that has an explicit size limit. Would suggest to limit it everywhere, including the Candid spec.

**Comment by timohanke** [comment]
I would also suggest to limit the length everywhere. I would then expose the textual encoding separately as a different module. If people have something that is not a Principal to encode or decode, including something longer, then they can use that module instead of abusing a Principal.fromText/toBlob combination or the reverse.

**Comment by crusso** [comment]
Interestingly, we discussed this in the PR that added principalOfBlob...
https://github.com/dfinity/motoko/pull/3050

**Comment by nomeata** [comment]
Oh, good that I am not completely contradicting myself :-D

**Comment by crusso** [comment]
> I would also suggest to limit the length everywhere. I would then expose the textual encoding separately as a different module. If people have something that is not a Principal to encode or decode, including something longer, then they can use that module instead of abusing Principal.fromText/toBlob in combination or the reverse of that.

Is that actually useful, more generally?
