### ISSUE TITLE
Moc Check Bug - 'public' as Variant Type

### ISSUE THREAD

**Issue by q-uint** [dfinity/motoko#4464]
I was converting [this file](https://github.com/dfinity/ic/blob/master/rs/nns/cmc/cmc.did#L3-L6) to Motoko and stumbled on the following bug:

```
module T {
    public type LogVisibility = { #controllers; #public };
};
```

`moc --check example.mo`

> syntax error [M0001], unexpected token 'public', expected one of token or <phrase> sequence:
  }
  <id> <annot_opt>

**Comment by crusso** [comment]
Quint, try:
```
module T {
    public type LogVisibility = { #controllers; #public_};
};
```

**Comment by q-uint** [comment]
Thanks @crusso!
