### ISSUE TITLE
 Streaming Chunks From A Canister

### ISSUE THREAD

**Issue by wirapratamaz** [dfinity/motoko#4473]
Hey there, I'm running into an issue where my stream callback isn't picking up changes to a blob that's supposed to update on a timer. It streams the initial blob just fine, but after that, it doesn't seem to notice when the blob's content changes. I'm using motoko on (https://github.com/dfinity/motoko/releases/tag/0.11.1) version. Any ideas on why this might be happening or how to fix it? Thanks!

**Comment by crusso** [comment]
Did you set up the timer as a recurring timer? Otherwise it just fires once.

**Comment by crusso** [comment]
It might be better to ask this as a question on the forum, with bits of relevant code.

**Comment by wirapratamaz** [comment]
Alright sir I already setup timer as a recurring timer
