### ISSUE TITLE
A mean to ask types confirmations without using DFX

### ISSUE THREAD

**Issue by vporton** [dfinity/motoko#4479]
I want a variation of `--stable-compatible` that would ask user for confirmations, when types are incompatible, like `dfx deploy` does.

This is because I want to do this without DFX (DFX is ill-designed: it recompiles everything even when there is no need).

**Comment by chenyan-dfinity** [comment]
In shell script, you can check the return code of `--stable-compatible`. If it's not 0, it's an error, and you can ask for confirmation in the script.

**Comment by chenyan-dfinity** [comment]
No, it doesn't. See https://github.com/dfinity/sdk/blob/master/src/dfx/src/lib/operations/canister/install_canister.rs#L373
