### ISSUE TITLE
Question: Shareable generics

### ISSUE THREAD

**Issue by Gekctek** [dfinity/motoko#4604]
I am trying to do the following
```

    public class Dao<system, TProposalContent, TProposalResult>(
        data : StableData<TProposalContent, TProposalResult>,
        onProposalExecute : Proposal<TProposalContent, TProposalResult> -> async* Result.Result<TProposalResult, Text>,
        onProposalReject : Proposal<TProposalContent, TProposalResult> -> async* (),
        onProposalValidate : TProposalContent -> async* Result.Result<(), [Text]>,
    ) {
    ```
    But I have an issue because `TProposalResult` isnt constrained to shareable so it gives me an error for the return type
    Is there a way around this?
    I need the async to be there
    
    Or any thoughts on alternative ways of handling this?

**Comment by crusso** [comment]
The best trick I've seen (due to @timohanke) is to pass in a mutable container for the result, and just return async* (), but the function will need to assign assign to the container...

ie. change:
```
onProposalExecute : Proposal<TProposalContent, TProposalResult> -> async* Result.Result<TProposalResult, Text>
```
to (something like) :

```
onProposalExecute : (Proposal<TProposalContent, TProposalResult>, { var result : ? Result.Result<TProposalResult, Text>}) :  -> async* ()
```

**Comment by Gekctek** [comment]
Thanks. Ill try that @crusso 

Is this a thing possible/planned for down the road?

**Comment by timohanke** [comment]
Wrote a blog post about the trick and a small mops package to help with it: [substack Motoko DeFi](https://open.substack.com/pub/motokodefi/p/asynchronous-generics-in-motoko?r=47u6i2&utm_campaign=post&utm_medium=web)

**Comment by Gekctek** [comment]
> Wrote a blog post about the trick and a small mops package to help with it: [substack Motoko DeFi](https://open.substack.com/pub/motokodefi/p/asynchronous-generics-in-motoko?r=47u6i2&utm_campaign=post&utm_medium=web)

Very cool. Thank you!
