### ISSUE TITLE
Feature: Motoko should support spread opearator

### ISSUE THREAD

**Issue by vporton** [dfinity/motoko#4605]
Motoko should support spread operator like as in JS or Rust. The proposed syntax:

```
let obj = { a = 1; c = 2};
{ a = 0; ..obj; c = 0 } // returns { a = 1; c = 0 }
```

**Comment by ggreif** [comment]
We have functional record updates, which don't sound like breakfast, but provide similar functionality:
``` Motoko
{ obj and otherObj with c = 0; d = 42 }
```
Your example (to get the same result would be written as
``` Motoko
let obj = { a = 1; c = 2 };
{ obj with c = 0 } // returns { a = 1; c = 0 }
```

They are being documented in #4594.

**Comment by ggreif** [comment]
@vporton feel free to close this if you are happy with the answer.

**Comment by vporton** [comment]
Please, provide similar functionality for actor types, too:

```motoko
let obj = actor { func a(); };
actor { obj with func c(); }

**Comment by ggreif** [comment]
> Please, provide similar functionality for actor types, too:

I had some deeper look into actor modules. It is not easy: #4371.

What you suggest won't fly unfortunately, as `actor { func a(); }` already installs that actor and as such the two actors only have a remote connection (at least).
