### ISSUE TITLE
Unable to deconstruct Nat8 object property

### ISSUE THREAD

**Issue by ByronBecker** [dfinity/motoko#4644]
See screenshot and error message taken directly from from my IDE this evening 👇 

![Screenshot 2024-07-31 at 18 50 13](https://github.com/user-attachments/assets/688f3d83-c0f1-4544-956c-a270828b0940)

It works if I don't deconstruct the object, and access the property after assignment 👇 
![Screenshot 2024-07-31 at 19 25 58](https://github.com/user-attachments/assets/cd26c660-629c-4c46-9640-808654f2f669)

**Comment by rossberg** [comment]
The error is correct, as you are trying to extract the property twice, once with `.decimal` (which already produces a Nat8) and then again by matching the result against the pattern `{decimal}` (where the RHS is no longer an object).

Either remove the `.decimal` or the braces around `decimal` on the left-hand side.
