### ISSUE TITLE
Unused identifier warning

### ISSUE THREAD

**Issue by infu** [dfinity/motoko#4755]
![image](https://github.com/user-attachments/assets/ae981d02-c0f5-4256-8d18-4ea76655a06f)

unused identifier b (delete or rename to wildcard `_` or `_b`)

For some reason this code is valid and will return 'b' while it shouldn't ? 
It will also show a warning it's unused.

**Comment by crusso** [comment]
That's actually not a bug. The value of a declaration used as the last expression of a block expression is the value of its rhs, unless the block has type (). 

The variable b is not referenced, hence the warning.

**Comment by crusso** [comment]
For example, this function returns (3,4), even though it bind nothing in the let.
> func f() : (Nat,Nat) {let _ = (3,4)};
let f : () -> (Nat, Nat) = <func>
> f();
(3, 4) : (Nat, Nat)
